// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: yandex/cloud/spark/v1/environment/environment_service.proto

package spark_environment

import (
	context "context"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvironmentService_Get_FullMethodName            = "/yandex.cloud.spark.v1.environment.EnvironmentService/Get"
	EnvironmentService_GetBase_FullMethodName        = "/yandex.cloud.spark.v1.environment.EnvironmentService/GetBase"
	EnvironmentService_List_FullMethodName           = "/yandex.cloud.spark.v1.environment.EnvironmentService/List"
	EnvironmentService_ListBase_FullMethodName       = "/yandex.cloud.spark.v1.environment.EnvironmentService/ListBase"
	EnvironmentService_Create_FullMethodName         = "/yandex.cloud.spark.v1.environment.EnvironmentService/Create"
	EnvironmentService_Update_FullMethodName         = "/yandex.cloud.spark.v1.environment.EnvironmentService/Update"
	EnvironmentService_Delete_FullMethodName         = "/yandex.cloud.spark.v1.environment.EnvironmentService/Delete"
	EnvironmentService_ListOperations_FullMethodName = "/yandex.cloud.spark.v1.environment.EnvironmentService/ListOperations"
)

// EnvironmentServiceClient is the client API for EnvironmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A set of methods for managing Environments.
type EnvironmentServiceClient interface {
	// Returns the specified Environment.
	Get(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	// Returns the specified Base Environment.
	GetBase(ctx context.Context, in *GetBaseEnvironmentRequest, opts ...grpc.CallOption) (*BaseEnvironment, error)
	// Retrieves a list of Environments.
	List(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error)
	// Retrieves a list of Base Environments.
	ListBase(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListBaseEnvironmentsResponse, error)
	// Creates a Environment.
	Create(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Updates the specified Environment.
	Update(ctx context.Context, in *UpdateEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Deletes the specified Environment.
	Delete(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Retrieves a list of Environment operations.
	ListOperations(ctx context.Context, in *ListEnvironmentOperationsRequest, opts ...grpc.CallOption) (*ListEnvironmentOperationsResponse, error)
}

type environmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvironmentServiceClient(cc grpc.ClientConnInterface) EnvironmentServiceClient {
	return &environmentServiceClient{cc}
}

func (c *environmentServiceClient) Get(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, EnvironmentService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) GetBase(ctx context.Context, in *GetBaseEnvironmentRequest, opts ...grpc.CallOption) (*BaseEnvironment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseEnvironment)
	err := c.cc.Invoke(ctx, EnvironmentService_GetBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) List(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentsResponse)
	err := c.cc.Invoke(ctx, EnvironmentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) ListBase(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListBaseEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBaseEnvironmentsResponse)
	err := c.cc.Invoke(ctx, EnvironmentService_ListBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) Create(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, EnvironmentService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) Update(ctx context.Context, in *UpdateEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, EnvironmentService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) Delete(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, EnvironmentService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *environmentServiceClient) ListOperations(ctx context.Context, in *ListEnvironmentOperationsRequest, opts ...grpc.CallOption) (*ListEnvironmentOperationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentOperationsResponse)
	err := c.cc.Invoke(ctx, EnvironmentService_ListOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvironmentServiceServer is the server API for EnvironmentService service.
// All implementations should embed UnimplementedEnvironmentServiceServer
// for forward compatibility.
//
// A set of methods for managing Environments.
type EnvironmentServiceServer interface {
	// Returns the specified Environment.
	Get(context.Context, *GetEnvironmentRequest) (*Environment, error)
	// Returns the specified Base Environment.
	GetBase(context.Context, *GetBaseEnvironmentRequest) (*BaseEnvironment, error)
	// Retrieves a list of Environments.
	List(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error)
	// Retrieves a list of Base Environments.
	ListBase(context.Context, *ListEnvironmentsRequest) (*ListBaseEnvironmentsResponse, error)
	// Creates a Environment.
	Create(context.Context, *CreateEnvironmentRequest) (*operation.Operation, error)
	// Updates the specified Environment.
	Update(context.Context, *UpdateEnvironmentRequest) (*operation.Operation, error)
	// Deletes the specified Environment.
	Delete(context.Context, *DeleteEnvironmentRequest) (*operation.Operation, error)
	// Retrieves a list of Environment operations.
	ListOperations(context.Context, *ListEnvironmentOperationsRequest) (*ListEnvironmentOperationsResponse, error)
}

// UnimplementedEnvironmentServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvironmentServiceServer struct{}

func (UnimplementedEnvironmentServiceServer) Get(context.Context, *GetEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEnvironmentServiceServer) GetBase(context.Context, *GetBaseEnvironmentRequest) (*BaseEnvironment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBase not implemented")
}
func (UnimplementedEnvironmentServiceServer) List(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEnvironmentServiceServer) ListBase(context.Context, *ListEnvironmentsRequest) (*ListBaseEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBase not implemented")
}
func (UnimplementedEnvironmentServiceServer) Create(context.Context, *CreateEnvironmentRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEnvironmentServiceServer) Update(context.Context, *UpdateEnvironmentRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEnvironmentServiceServer) Delete(context.Context, *DeleteEnvironmentRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEnvironmentServiceServer) ListOperations(context.Context, *ListEnvironmentOperationsRequest) (*ListEnvironmentOperationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperations not implemented")
}
func (UnimplementedEnvironmentServiceServer) testEmbeddedByValue() {}

// UnsafeEnvironmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvironmentServiceServer will
// result in compilation errors.
type UnsafeEnvironmentServiceServer interface {
	mustEmbedUnimplementedEnvironmentServiceServer()
}

func RegisterEnvironmentServiceServer(s grpc.ServiceRegistrar, srv EnvironmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnvironmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvironmentService_ServiceDesc, srv)
}

func _EnvironmentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).Get(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_GetBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).GetBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_GetBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).GetBase(ctx, req.(*GetBaseEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).List(ctx, req.(*ListEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_ListBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).ListBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_ListBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).ListBase(ctx, req.(*ListEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).Create(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).Update(ctx, req.(*UpdateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).Delete(ctx, req.(*DeleteEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvironmentService_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvironmentServiceServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvironmentService_ListOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvironmentServiceServer).ListOperations(ctx, req.(*ListEnvironmentOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvironmentService_ServiceDesc is the grpc.ServiceDesc for EnvironmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvironmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yandex.cloud.spark.v1.environment.EnvironmentService",
	HandlerType: (*EnvironmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EnvironmentService_Get_Handler,
		},
		{
			MethodName: "GetBase",
			Handler:    _EnvironmentService_GetBase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _EnvironmentService_List_Handler,
		},
		{
			MethodName: "ListBase",
			Handler:    _EnvironmentService_ListBase_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _EnvironmentService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EnvironmentService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EnvironmentService_Delete_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _EnvironmentService_ListOperations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yandex/cloud/spark/v1/environment/environment_service.proto",
}
