// Code generated by protoc-gen-goext. DO NOT EDIT.

package speechsense

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

func (m *Points) SetQuiz(v []*Quiz) {
	m.Quiz = v
}

func (m *Quiz) SetRequest(v string) {
	m.Request = v
}

func (m *Quiz) SetResponse(v *wrapperspb.StringValue) {
	m.Response = v
}

func (m *Quiz) SetId(v string) {
	m.Id = v
}
