// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yandex/cloud/organizationmanager/v1/saml/federation.proto

package saml

import (
	_ "github.com/yandex-cloud/go-genproto/yandex/cloud"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingType int32

const (
	BindingType_BINDING_TYPE_UNSPECIFIED BindingType = 0
	// HTTP POST binding.
	BindingType_POST BindingType = 1
	// HTTP redirect binding.
	BindingType_REDIRECT BindingType = 2
	// HTTP artifact binding.
	BindingType_ARTIFACT BindingType = 3
)

// Enum value maps for BindingType.
var (
	BindingType_name = map[int32]string{
		0: "BINDING_TYPE_UNSPECIFIED",
		1: "POST",
		2: "REDIRECT",
		3: "ARTIFACT",
	}
	BindingType_value = map[string]int32{
		"BINDING_TYPE_UNSPECIFIED": 0,
		"POST":                     1,
		"REDIRECT":                 2,
		"ARTIFACT":                 3,
	}
)

func (x BindingType) Enum() *BindingType {
	p := new(BindingType)
	*p = x
	return p
}

func (x BindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_organizationmanager_v1_saml_federation_proto_enumTypes[0].Descriptor()
}

func (BindingType) Type() protoreflect.EnumType {
	return &file_yandex_cloud_organizationmanager_v1_saml_federation_proto_enumTypes[0]
}

func (x BindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingType.Descriptor instead.
func (BindingType) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescGZIP(), []int{0}
}

// A federation.
// For more information, see [SAML-compatible identity federations](/docs/iam/concepts/federations).
type Federation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the federation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the organization that the federation belongs to.
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Name of the federation.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the federation.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Browser cookie lifetime in seconds.
	// If the cookie is still valid, the management console
	// authenticates the user immediately and redirects them to the home page.
	CookieMaxAge *durationpb.Duration `protobuf:"bytes,6,opt,name=cookie_max_age,json=cookieMaxAge,proto3" json:"cookie_max_age,omitempty"`
	// Add new users automatically on successful authentication.
	// The user becomes member of the organization automatically,
	// but you need to grant other roles to them.
	//
	// If the value is `false`, users who aren't added to the organization
	// can't log in, even if they have authenticated on your server.
	AutoCreateAccountOnLogin bool `protobuf:"varint,7,opt,name=auto_create_account_on_login,json=autoCreateAccountOnLogin,proto3" json:"auto_create_account_on_login,omitempty"`
	// ID of the IdP server to be used for authentication.
	// The IdP server also responds to IAM with this ID after the user authenticates.
	Issuer string `protobuf:"bytes,8,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Single sign-on endpoint binding type. Most Identity Providers support the `POST` binding type.
	//
	// SAML Binding is a mapping of a SAML protocol message onto standard messaging
	// formats and/or communications protocols.
	SsoBinding BindingType `protobuf:"varint,9,opt,name=sso_binding,json=ssoBinding,proto3,enum=yandex.cloud.organizationmanager.v1.saml.BindingType" json:"sso_binding,omitempty"`
	// Single sign-on endpoint URL.
	// Specify the link to the IdP login page here.
	SsoUrl string `protobuf:"bytes,10,opt,name=sso_url,json=ssoUrl,proto3" json:"sso_url,omitempty"`
	// Federation security settings.
	SecuritySettings *FederationSecuritySettings `protobuf:"bytes,11,opt,name=security_settings,json=securitySettings,proto3" json:"security_settings,omitempty"`
	// Use case insensitive Name IDs.
	CaseInsensitiveNameIds bool `protobuf:"varint,12,opt,name=case_insensitive_name_ids,json=caseInsensitiveNameIds,proto3" json:"case_insensitive_name_ids,omitempty"`
	// Resource labels as “ key:value “ pairs. Maximum of 64 per resource.
	Labels        map[string]string `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Federation) Reset() {
	*x = Federation{}
	mi := &file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Federation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Federation) ProtoMessage() {}

func (x *Federation) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Federation.ProtoReflect.Descriptor instead.
func (*Federation) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescGZIP(), []int{0}
}

func (x *Federation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Federation) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Federation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Federation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Federation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Federation) GetCookieMaxAge() *durationpb.Duration {
	if x != nil {
		return x.CookieMaxAge
	}
	return nil
}

func (x *Federation) GetAutoCreateAccountOnLogin() bool {
	if x != nil {
		return x.AutoCreateAccountOnLogin
	}
	return false
}

func (x *Federation) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Federation) GetSsoBinding() BindingType {
	if x != nil {
		return x.SsoBinding
	}
	return BindingType_BINDING_TYPE_UNSPECIFIED
}

func (x *Federation) GetSsoUrl() string {
	if x != nil {
		return x.SsoUrl
	}
	return ""
}

func (x *Federation) GetSecuritySettings() *FederationSecuritySettings {
	if x != nil {
		return x.SecuritySettings
	}
	return nil
}

func (x *Federation) GetCaseInsensitiveNameIds() bool {
	if x != nil {
		return x.CaseInsensitiveNameIds
	}
	return false
}

func (x *Federation) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Federation security settings.
type FederationSecuritySettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable encrypted assertions.
	EncryptedAssertions bool `protobuf:"varint,1,opt,name=encrypted_assertions,json=encryptedAssertions,proto3" json:"encrypted_assertions,omitempty"`
	// Value parameter ForceAuthn in SAMLRequest.
	ForceAuthn    bool `protobuf:"varint,2,opt,name=force_authn,json=forceAuthn,proto3" json:"force_authn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationSecuritySettings) Reset() {
	*x = FederationSecuritySettings{}
	mi := &file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationSecuritySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationSecuritySettings) ProtoMessage() {}

func (x *FederationSecuritySettings) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationSecuritySettings.ProtoReflect.Descriptor instead.
func (*FederationSecuritySettings) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescGZIP(), []int{1}
}

func (x *FederationSecuritySettings) GetEncryptedAssertions() bool {
	if x != nil {
		return x.EncryptedAssertions
	}
	return false
}

func (x *FederationSecuritySettings) GetForceAuthn() bool {
	if x != nil {
		return x.ForceAuthn
	}
	return false
}

var File_yandex_cloud_organizationmanager_v1_saml_federation_proto protoreflect.FileDescriptor

const file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDesc = "" +
	"\n" +
	"9yandex/cloud/organizationmanager/v1/saml/federation.proto\x12(yandex.cloud.organizationmanager.v1.saml\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dyandex/cloud/validation.proto\"\xf0\x06\n" +
	"\n" +
	"Federation\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\tB\f\xe8\xc71\x01\x8a\xc81\x04<=50R\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x129\n" +
	"\x04name\x18\x03 \x01(\tB%\xe8\xc71\x01\xf2\xc71\x1d|[a-z][-a-z0-9]{1,61}[a-z0-9]R\x04name\x12+\n" +
	"\vdescription\x18\x04 \x01(\tB\t\x8a\xc81\x05<=256R\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12L\n" +
	"\x0ecookie_max_age\x18\x06 \x01(\v2\x19.google.protobuf.DurationB\v\xfa\xc71\a10m-12hR\fcookieMaxAge\x12>\n" +
	"\x1cauto_create_account_on_login\x18\a \x01(\bR\x18autoCreateAccountOnLogin\x12&\n" +
	"\x06issuer\x18\b \x01(\tB\x0e\xe8\xc71\x01\x8a\xc81\x06<=8000R\x06issuer\x12V\n" +
	"\vsso_binding\x18\t \x01(\x0e25.yandex.cloud.organizationmanager.v1.saml.BindingTypeR\n" +
	"ssoBinding\x12'\n" +
	"\asso_url\x18\n" +
	" \x01(\tB\x0e\xe8\xc71\x01\x8a\xc81\x06<=8000R\x06ssoUrl\x12q\n" +
	"\x11security_settings\x18\v \x01(\v2D.yandex.cloud.organizationmanager.v1.saml.FederationSecuritySettingsR\x10securitySettings\x129\n" +
	"\x19case_insensitive_name_ids\x18\f \x01(\bR\x16caseInsensitiveNameIds\x12X\n" +
	"\x06labels\x18\r \x03(\v2@.yandex.cloud.organizationmanager.v1.saml.Federation.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x1aFederationSecuritySettings\x121\n" +
	"\x14encrypted_assertions\x18\x01 \x01(\bR\x13encryptedAssertions\x12\x1f\n" +
	"\vforce_authn\x18\x02 \x01(\bR\n" +
	"forceAuthn*Q\n" +
	"\vBindingType\x12\x1c\n" +
	"\x18BINDING_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\f\n" +
	"\bREDIRECT\x10\x02\x12\f\n" +
	"\bARTIFACT\x10\x03B\x81\x01\n" +
	",yandex.cloud.api.organizationmanager.v1.samlZQgithub.com/yandex-cloud/go-genproto/yandex/cloud/organizationmanager/v1/saml;samlb\x06proto3"

var (
	file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescOnce sync.Once
	file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescData []byte
)

func file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescGZIP() []byte {
	file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDesc), len(file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDesc)))
	})
	return file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDescData
}

var file_yandex_cloud_organizationmanager_v1_saml_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yandex_cloud_organizationmanager_v1_saml_federation_proto_goTypes = []any{
	(BindingType)(0),                   // 0: yandex.cloud.organizationmanager.v1.saml.BindingType
	(*Federation)(nil),                 // 1: yandex.cloud.organizationmanager.v1.saml.Federation
	(*FederationSecuritySettings)(nil), // 2: yandex.cloud.organizationmanager.v1.saml.FederationSecuritySettings
	nil,                                // 3: yandex.cloud.organizationmanager.v1.saml.Federation.LabelsEntry
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 5: google.protobuf.Duration
}
var file_yandex_cloud_organizationmanager_v1_saml_federation_proto_depIdxs = []int32{
	4, // 0: yandex.cloud.organizationmanager.v1.saml.Federation.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: yandex.cloud.organizationmanager.v1.saml.Federation.cookie_max_age:type_name -> google.protobuf.Duration
	0, // 2: yandex.cloud.organizationmanager.v1.saml.Federation.sso_binding:type_name -> yandex.cloud.organizationmanager.v1.saml.BindingType
	2, // 3: yandex.cloud.organizationmanager.v1.saml.Federation.security_settings:type_name -> yandex.cloud.organizationmanager.v1.saml.FederationSecuritySettings
	3, // 4: yandex.cloud.organizationmanager.v1.saml.Federation.labels:type_name -> yandex.cloud.organizationmanager.v1.saml.Federation.LabelsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_yandex_cloud_organizationmanager_v1_saml_federation_proto_init() }
func file_yandex_cloud_organizationmanager_v1_saml_federation_proto_init() {
	if File_yandex_cloud_organizationmanager_v1_saml_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDesc), len(file_yandex_cloud_organizationmanager_v1_saml_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_organizationmanager_v1_saml_federation_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_organizationmanager_v1_saml_federation_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_organizationmanager_v1_saml_federation_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_organizationmanager_v1_saml_federation_proto_msgTypes,
	}.Build()
	File_yandex_cloud_organizationmanager_v1_saml_federation_proto = out.File
	file_yandex_cloud_organizationmanager_v1_saml_federation_proto_goTypes = nil
	file_yandex_cloud_organizationmanager_v1_saml_federation_proto_depIdxs = nil
}
