// Code generated by protoc-gen-goext. DO NOT EDIT.

package speechsense

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (m *TextRequest) SetEntries(v []*TextEntry) {
	m.Entries = v
}

func (m *TextEntry) SetChannelNumber(v int64) {
	m.ChannelNumber = v
}

func (m *TextEntry) SetTimestamp(v *timestamppb.Timestamp) {
	m.Timestamp = v
}

func (m *TextEntry) SetText(v string) {
	m.Text = v
}
