// Code generated by protoc-gen-goext. DO NOT EDIT.

package datasphere

func (m *FileMetadata) SetProjectId(v string) {
	m.ProjectId = v
}

func (m *FileMetadata) SetPath(v string) {
	m.Path = v
}

func (m *FileMetadata) SetSizeBytes(v int64) {
	m.SizeBytes = v
}

type UploadFileRequest_Message = isUploadFileRequest_Message

func (m *UploadFileRequest) SetMessage(v UploadFileRequest_Message) {
	m.Message = v
}

func (m *UploadFileRequest) SetMetadata(v *FileMetadata) {
	m.Message = &UploadFileRequest_Metadata{
		Metadata: v,
	}
}

func (m *UploadFileRequest) SetChunk(v []byte) {
	m.Message = &UploadFileRequest_Chunk{
		Chunk: v,
	}
}

func (m *UploadFileResponse) SetMetadata(v *FileMetadata) {
	m.Metadata = v
}

func (m *DownloadFileRequest) SetProjectId(v string) {
	m.ProjectId = v
}

func (m *DownloadFileRequest) SetFilePath(v string) {
	m.FilePath = v
}

type DownloadFileResponse_Message = isDownloadFileResponse_Message

func (m *DownloadFileResponse) SetMessage(v DownloadFileResponse_Message) {
	m.Message = v
}

func (m *DownloadFileResponse) SetMetadata(v *FileMetadata) {
	m.Message = &DownloadFileResponse_Metadata{
		Metadata: v,
	}
}

func (m *DownloadFileResponse) SetChunk(v []byte) {
	m.Message = &DownloadFileResponse_Chunk{
		Chunk: v,
	}
}
