// Code generated by protoc-gen-goext. DO NOT EDIT.

package baremetal

func (m *GetConfigurationRequest) SetConfigurationId(v string) {
	m.ConfigurationId = v
}

func (m *GetConfigurationRequest) SetFolderId(v string) {
	m.FolderId = v
}

func (m *ListConfigurationsRequest) SetPageSize(v int64) {
	m.PageSize = v
}

func (m *ListConfigurationsRequest) SetPageToken(v string) {
	m.PageToken = v
}

func (m *ListConfigurationsRequest) SetOrderBy(v string) {
	m.OrderBy = v
}

func (m *ListConfigurationsRequest) SetFilter(v string) {
	m.Filter = v
}

func (m *ListConfigurationsRequest) SetFolderId(v string) {
	m.FolderId = v
}

func (m *ListConfigurationsResponse) SetConfigurations(v []*Configuration) {
	m.Configurations = v
}

func (m *ListConfigurationsResponse) SetNextPageToken(v string) {
	m.NextPageToken = v
}
