// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yandex/cloud/baremetal/v1alpha/disk.proto

package baremetal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Disk drive type.
type DiskDriveType int32

const (
	// Unspecified disk drive type.
	DiskDriveType_DISK_DRIVE_TYPE_UNSPECIFIED DiskDriveType = 0
	// Hard disk drive (magnetic storage).
	DiskDriveType_HDD DiskDriveType = 1
	// Solid state drive with SATA/SAS interface.
	DiskDriveType_SSD DiskDriveType = 2
	// Solid state drive with NVMe interface.
	DiskDriveType_NVME DiskDriveType = 3
)

// Enum value maps for DiskDriveType.
var (
	DiskDriveType_name = map[int32]string{
		0: "DISK_DRIVE_TYPE_UNSPECIFIED",
		1: "HDD",
		2: "SSD",
		3: "NVME",
	}
	DiskDriveType_value = map[string]int32{
		"DISK_DRIVE_TYPE_UNSPECIFIED": 0,
		"HDD":                         1,
		"SSD":                         2,
		"NVME":                        3,
	}
)

func (x DiskDriveType) Enum() *DiskDriveType {
	p := new(DiskDriveType)
	*p = x
	return p
}

func (x DiskDriveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskDriveType) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_baremetal_v1alpha_disk_proto_enumTypes[0].Descriptor()
}

func (DiskDriveType) Type() protoreflect.EnumType {
	return &file_yandex_cloud_baremetal_v1alpha_disk_proto_enumTypes[0]
}

func (x DiskDriveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskDriveType.Descriptor instead.
func (DiskDriveType) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescGZIP(), []int{0}
}

// Disk.
type Disk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the disk.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of the disk drive.
	Type DiskDriveType `protobuf:"varint,2,opt,name=type,proto3,enum=yandex.cloud.baremetal.v1alpha.DiskDriveType" json:"type,omitempty"`
	// Size of the disk in gibibytes (2^30 bytes).
	SizeGib       int64 `protobuf:"varint,3,opt,name=size_gib,json=sizeGib,proto3" json:"size_gib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_yandex_cloud_baremetal_v1alpha_disk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v1alpha_disk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescGZIP(), []int{0}
}

func (x *Disk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Disk) GetType() DiskDriveType {
	if x != nil {
		return x.Type
	}
	return DiskDriveType_DISK_DRIVE_TYPE_UNSPECIFIED
}

func (x *Disk) GetSizeGib() int64 {
	if x != nil {
		return x.SizeGib
	}
	return 0
}

var File_yandex_cloud_baremetal_v1alpha_disk_proto protoreflect.FileDescriptor

const file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDesc = "" +
	"\n" +
	")yandex/cloud/baremetal/v1alpha/disk.proto\x12\x1eyandex.cloud.baremetal.v1alpha\"t\n" +
	"\x04Disk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\x04type\x18\x02 \x01(\x0e2-.yandex.cloud.baremetal.v1alpha.DiskDriveTypeR\x04type\x12\x19\n" +
	"\bsize_gib\x18\x03 \x01(\x03R\asizeGib*L\n" +
	"\rDiskDriveType\x12\x1f\n" +
	"\x1bDISK_DRIVE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03HDD\x10\x01\x12\a\n" +
	"\x03SSD\x10\x02\x12\b\n" +
	"\x04NVME\x10\x03Br\n" +
	"\"yandex.cloud.api.baremetal.v1alphaZLgithub.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha;baremetalb\x06proto3"

var (
	file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescOnce sync.Once
	file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescData []byte
)

func file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescGZIP() []byte {
	file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDesc), len(file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDesc)))
	})
	return file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDescData
}

var file_yandex_cloud_baremetal_v1alpha_disk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yandex_cloud_baremetal_v1alpha_disk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yandex_cloud_baremetal_v1alpha_disk_proto_goTypes = []any{
	(DiskDriveType)(0), // 0: yandex.cloud.baremetal.v1alpha.DiskDriveType
	(*Disk)(nil),       // 1: yandex.cloud.baremetal.v1alpha.Disk
}
var file_yandex_cloud_baremetal_v1alpha_disk_proto_depIdxs = []int32{
	0, // 0: yandex.cloud.baremetal.v1alpha.Disk.type:type_name -> yandex.cloud.baremetal.v1alpha.DiskDriveType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yandex_cloud_baremetal_v1alpha_disk_proto_init() }
func file_yandex_cloud_baremetal_v1alpha_disk_proto_init() {
	if File_yandex_cloud_baremetal_v1alpha_disk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDesc), len(file_yandex_cloud_baremetal_v1alpha_disk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_baremetal_v1alpha_disk_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_baremetal_v1alpha_disk_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_baremetal_v1alpha_disk_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_baremetal_v1alpha_disk_proto_msgTypes,
	}.Build()
	File_yandex_cloud_baremetal_v1alpha_disk_proto = out.File
	file_yandex_cloud_baremetal_v1alpha_disk_proto_goTypes = nil
	file_yandex_cloud_baremetal_v1alpha_disk_proto_depIdxs = nil
}
