// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yandex/cloud/baremetal/v1alpha/image.proto

package baremetal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Image status.
type Image_Status int32

const (
	// Unspecified image status.
	Image_STATUS_UNSPECIFIED Image_Status = 0
	// Image is being created.
	Image_CREATING Image_Status = 1
	// Image is ready to use.
	Image_READY Image_Status = 2
	// Image encountered an error.
	Image_ERROR Image_Status = 3
	// Image is being deleted.
	Image_DELETING Image_Status = 4
	// Image is being updated.
	Image_UPDATING Image_Status = 5
)

// Enum value maps for Image_Status.
var (
	Image_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "CREATING",
		2: "READY",
		3: "ERROR",
		4: "DELETING",
		5: "UPDATING",
	}
	Image_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"CREATING":           1,
		"READY":              2,
		"ERROR":              3,
		"DELETING":           4,
		"UPDATING":           5,
	}
)

func (x Image_Status) Enum() *Image_Status {
	p := new(Image_Status)
	*p = x
	return p
}

func (x Image_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Image_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_baremetal_v1alpha_image_proto_enumTypes[0].Descriptor()
}

func (Image_Status) Type() protoreflect.EnumType {
	return &file_yandex_cloud_baremetal_v1alpha_image_proto_enumTypes[0]
}

func (x Image_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Image_Status.Descriptor instead.
func (Image_Status) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescGZIP(), []int{0, 0}
}

// An Image resource.
type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the image.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the folder that the image belongs to.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// Name of the image.
	// The name is unique within the folder.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the image.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// MD5 checksum of the image.
	Checksum string `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Status of the image.
	Status Image_Status `protobuf:"varint,7,opt,name=status,proto3,enum=yandex.cloud.baremetal.v1alpha.Image_Status" json:"status,omitempty"`
	// Creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Resource labels as `key:value` pairs.
	Labels        map[string]string `protobuf:"bytes,200,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_yandex_cloud_baremetal_v1alpha_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v1alpha_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Image) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Image) GetStatus() Image_Status {
	if x != nil {
		return x.Status
	}
	return Image_STATUS_UNSPECIFIED
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_yandex_cloud_baremetal_v1alpha_image_proto protoreflect.FileDescriptor

const file_yandex_cloud_baremetal_v1alpha_image_proto_rawDesc = "" +
	"\n" +
	"*yandex/cloud/baremetal/v1alpha/image.proto\x12\x1eyandex.cloud.baremetal.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x04\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12D\n" +
	"\x06status\x18\a \x01(\x0e2,.yandex.cloud.baremetal.v1alpha.Image.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12J\n" +
	"\x06labels\x18\xc8\x01 \x03(\v21.yandex.cloud.baremetal.v1alpha.Image.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\f\n" +
	"\bDELETING\x10\x04\x12\f\n" +
	"\bUPDATING\x10\x05J\x04\b\x03\x10\x04J\x04\b\b\x10dJ\x05\be\x10\xc8\x01Br\n" +
	"\"yandex.cloud.api.baremetal.v1alphaZLgithub.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v1alpha;baremetalb\x06proto3"

var (
	file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescOnce sync.Once
	file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescData []byte
)

func file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescGZIP() []byte {
	file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v1alpha_image_proto_rawDesc), len(file_yandex_cloud_baremetal_v1alpha_image_proto_rawDesc)))
	})
	return file_yandex_cloud_baremetal_v1alpha_image_proto_rawDescData
}

var file_yandex_cloud_baremetal_v1alpha_image_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yandex_cloud_baremetal_v1alpha_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yandex_cloud_baremetal_v1alpha_image_proto_goTypes = []any{
	(Image_Status)(0),             // 0: yandex.cloud.baremetal.v1alpha.Image.Status
	(*Image)(nil),                 // 1: yandex.cloud.baremetal.v1alpha.Image
	nil,                           // 2: yandex.cloud.baremetal.v1alpha.Image.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_yandex_cloud_baremetal_v1alpha_image_proto_depIdxs = []int32{
	0, // 0: yandex.cloud.baremetal.v1alpha.Image.status:type_name -> yandex.cloud.baremetal.v1alpha.Image.Status
	3, // 1: yandex.cloud.baremetal.v1alpha.Image.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: yandex.cloud.baremetal.v1alpha.Image.labels:type_name -> yandex.cloud.baremetal.v1alpha.Image.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yandex_cloud_baremetal_v1alpha_image_proto_init() }
func file_yandex_cloud_baremetal_v1alpha_image_proto_init() {
	if File_yandex_cloud_baremetal_v1alpha_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v1alpha_image_proto_rawDesc), len(file_yandex_cloud_baremetal_v1alpha_image_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_baremetal_v1alpha_image_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_baremetal_v1alpha_image_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_baremetal_v1alpha_image_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_baremetal_v1alpha_image_proto_msgTypes,
	}.Build()
	File_yandex_cloud_baremetal_v1alpha_image_proto = out.File
	file_yandex_cloud_baremetal_v1alpha_image_proto_goTypes = nil
	file_yandex_cloud_baremetal_v1alpha_image_proto_depIdxs = nil
}
