// Code generated by protoc-gen-goext. DO NOT EDIT.

package baremetal

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (m *PrivateCloudConnection) SetId(v string) {
	m.Id = v
}

func (m *PrivateCloudConnection) SetFolderId(v string) {
	m.FolderId = v
}

func (m *PrivateCloudConnection) SetCloudId(v string) {
	m.CloudId = v
}

func (m *PrivateCloudConnection) SetRoutingInstanceId(v string) {
	m.RoutingInstanceId = v
}

func (m *PrivateCloudConnection) SetVrfId(v string) {
	m.VrfId = v
}

func (m *PrivateCloudConnection) SetStatus(v PrivateCloudConnection_Status) {
	m.Status = v
}

func (m *PrivateCloudConnection) SetCreatedAt(v *timestamppb.Timestamp) {
	m.CreatedAt = v
}
