// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: yandex/cloud/baremetal/v2/private_subnet_service.proto

package baremetal

import (
	_ "github.com/yandex-cloud/go-genproto/yandex/cloud"
	_ "github.com/yandex-cloud/go-genproto/yandex/cloud/api"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPrivateSubnetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the parent cloud.
	//
	// To get the cloud ID, use a [yandex.cloud.resourcemanager.v1.CloudService.List] request.
	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the parent folder.
	//
	// To get the folder ID, use a [yandex.cloud.resourcemanager.v1.FolderService.List] request.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// ID of the PrivateSubnet resource to return.
	//
	// To get the private subnet ID use a [PrivateSubnetService.List] request.
	PrivateSubnetId string `protobuf:"bytes,3,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPrivateSubnetRequest) Reset() {
	*x = GetPrivateSubnetRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateSubnetRequest) ProtoMessage() {}

func (x *GetPrivateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateSubnetRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPrivateSubnetRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *GetPrivateSubnetRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *GetPrivateSubnetRequest) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

type ListPrivateSubnetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the parent cloud.
	//
	// To get the cloud ID, use a [yandex.cloud.resourcemanager.v1.CloudService.List] request.
	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the parent folder.
	//
	// To get the folder ID, use a [yandex.cloud.resourcemanager.v1.FolderService.List] request.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// The maximum number of results per page to return. If the number of available
	// results is greater than `page_size`,
	// the service returns a [ListPrivateSubnetsResponse.next_page_token]
	// that can be used to get the next page of results in subsequent list requests.
	// Default value is 20.
	PageSize int64 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token. To get the next page of results, set `page_token` to the
	// [ListPrivateSubnetsResponse.next_page_token] returned by a previous list request.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sorting order for the listing. Follows the [AIP-132](https://google.aip.dev/132) `order_by` format:
	// `"field [asc|desc]"`, e.g. `"createTime desc"`.
	//
	// Supported fields: `privateSubnetId`, `createTime`, `updateTime`.
	// Default order: `privateSubnetId asc`.
	OrderBy string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Filter expression following [AIP-160](https://google.aip.dev/160).
	//
	// Supported fields and operators:
	// - `privateSubnetId`, `name`, `hardwarePoolId` - `=`, `!=`, `:` (contains)
	// - `state` - `=`, `!=`
	// - `vrfOptions.vrfId` - `=`, `!=`, `:` (contains)
	//
	// Example: `state = "READY" AND vrfOptions.vrfId = "enp1234abcd"`.
	Filter        string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateSubnetsRequest) Reset() {
	*x = ListPrivateSubnetsRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateSubnetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateSubnetsRequest) ProtoMessage() {}

func (x *ListPrivateSubnetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateSubnetsRequest.ProtoReflect.Descriptor instead.
func (*ListPrivateSubnetsRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPrivateSubnetsRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *ListPrivateSubnetsRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ListPrivateSubnetsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrivateSubnetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPrivateSubnetsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListPrivateSubnetsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListPrivateSubnetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of PrivateSubnet resources.
	PrivateSubnets []*PrivateSubnet `protobuf:"bytes,1,rep,name=private_subnets,json=privateSubnets,proto3" json:"private_subnets,omitempty"`
	// Token for getting the next page of the list. If the number of results is greater than
	// [ListPrivateSubnetsRequest.page_size], use `next_page_token` as the value
	// for the [ListPrivateSubnetsRequest.page_token] parameter in the next list request.
	//
	// Each subsequent page will have its own `next_page_token` to continue paging through the results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateSubnetsResponse) Reset() {
	*x = ListPrivateSubnetsResponse{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateSubnetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateSubnetsResponse) ProtoMessage() {}

func (x *ListPrivateSubnetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateSubnetsResponse.ProtoReflect.Descriptor instead.
func (*ListPrivateSubnetsResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPrivateSubnetsResponse) GetPrivateSubnets() []*PrivateSubnet {
	if x != nil {
		return x.PrivateSubnets
	}
	return nil
}

func (x *ListPrivateSubnetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreatePrivateSubnetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the parent cloud.
	//
	// To get the cloud ID, use a [yandex.cloud.resourcemanager.v1.CloudService.List] request.
	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the parent folder.
	//
	// To get the folder ID, use a [yandex.cloud.resourcemanager.v1.FolderService.List] request.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// The private subnet to create.
	PrivateSubnet *PrivateSubnet `protobuf:"bytes,3,opt,name=private_subnet,json=privateSubnet,proto3" json:"private_subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrivateSubnetRequest) Reset() {
	*x = CreatePrivateSubnetRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateSubnetRequest) ProtoMessage() {}

func (x *CreatePrivateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateSubnetRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePrivateSubnetRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *CreatePrivateSubnetRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *CreatePrivateSubnetRequest) GetPrivateSubnet() *PrivateSubnet {
	if x != nil {
		return x.PrivateSubnet
	}
	return nil
}

type CreatePrivateSubnetMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the private subnet that is being created.
	PrivateSubnetId string `protobuf:"bytes,1,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePrivateSubnetMetadata) Reset() {
	*x = CreatePrivateSubnetMetadata{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateSubnetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateSubnetMetadata) ProtoMessage() {}

func (x *CreatePrivateSubnetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateSubnetMetadata.ProtoReflect.Descriptor instead.
func (*CreatePrivateSubnetMetadata) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePrivateSubnetMetadata) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

type UpdatePrivateSubnetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PrivateSubnet object to be updated.
	PrivateSubnet *PrivateSubnet `protobuf:"bytes,1,opt,name=private_subnet,json=privateSubnet,proto3" json:"private_subnet,omitempty"`
	// Field mask that specifies which fields of the PrivateSubnet resource are going to be updated.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePrivateSubnetRequest) Reset() {
	*x = UpdatePrivateSubnetRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivateSubnetRequest) ProtoMessage() {}

func (x *UpdatePrivateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivateSubnetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePrivateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePrivateSubnetRequest) GetPrivateSubnet() *PrivateSubnet {
	if x != nil {
		return x.PrivateSubnet
	}
	return nil
}

func (x *UpdatePrivateSubnetRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdatePrivateSubnetMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the PrivateSubnet resource that is being updated.
	PrivateSubnetId string `protobuf:"bytes,1,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePrivateSubnetMetadata) Reset() {
	*x = UpdatePrivateSubnetMetadata{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivateSubnetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivateSubnetMetadata) ProtoMessage() {}

func (x *UpdatePrivateSubnetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivateSubnetMetadata.ProtoReflect.Descriptor instead.
func (*UpdatePrivateSubnetMetadata) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePrivateSubnetMetadata) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

type DeletePrivateSubnetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the parent cloud.
	//
	// To get the cloud ID, use a [yandex.cloud.resourcemanager.v1.CloudService.List] request.
	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the parent folder.
	//
	// To get the folder ID, use a [yandex.cloud.resourcemanager.v1.FolderService.List] request.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// ID of the private subnet to delete.
	//
	// To get the private subnet ID, use a [PrivateSubnetService.List] request.
	PrivateSubnetId string `protobuf:"bytes,3,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeletePrivateSubnetRequest) Reset() {
	*x = DeletePrivateSubnetRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrivateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrivateSubnetRequest) ProtoMessage() {}

func (x *DeletePrivateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrivateSubnetRequest.ProtoReflect.Descriptor instead.
func (*DeletePrivateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePrivateSubnetRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *DeletePrivateSubnetRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *DeletePrivateSubnetRequest) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

type DeletePrivateSubnetMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the PrivateSubnet resource that is being deleted.
	PrivateSubnetId string `protobuf:"bytes,1,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeletePrivateSubnetMetadata) Reset() {
	*x = DeletePrivateSubnetMetadata{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrivateSubnetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrivateSubnetMetadata) ProtoMessage() {}

func (x *DeletePrivateSubnetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrivateSubnetMetadata.ProtoReflect.Descriptor instead.
func (*DeletePrivateSubnetMetadata) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePrivateSubnetMetadata) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

type ListPrivateSubnetOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the parent cloud.
	//
	// To get the cloud ID, use a [yandex.cloud.resourcemanager.v1.CloudService.List] request.
	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the parent folder.
	//
	// To get the folder ID, use a [yandex.cloud.resourcemanager.v1.FolderService.List] request.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// ID of the private subnet to list operations for.
	//
	// To get the private subnet ID, use a [PrivateSubnetService.List] request.
	PrivateSubnetId string `protobuf:"bytes,3,opt,name=private_subnet_id,json=privateSubnetId,proto3" json:"private_subnet_id,omitempty"`
	// The maximum number of results per page to return. If the number of available
	// results is greater than `page_size`,
	// the service returns a [ListPrivateSubnetOperationsResponse.next_page_token]
	// that can be used to get the next page of results in subsequent list requests.
	// Default value is 20.
	PageSize int64 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token. To get the next page of results, set `page_token` to the
	// [ListPrivateSubnetOperationsResponse.next_page_token] returned by a previous list request.
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateSubnetOperationsRequest) Reset() {
	*x = ListPrivateSubnetOperationsRequest{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateSubnetOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateSubnetOperationsRequest) ProtoMessage() {}

func (x *ListPrivateSubnetOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateSubnetOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListPrivateSubnetOperationsRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListPrivateSubnetOperationsRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *ListPrivateSubnetOperationsRequest) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *ListPrivateSubnetOperationsRequest) GetPrivateSubnetId() string {
	if x != nil {
		return x.PrivateSubnetId
	}
	return ""
}

func (x *ListPrivateSubnetOperationsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrivateSubnetOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPrivateSubnetOperationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of operations for the specified Image resource.
	Operations []*operation.Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	// Token for getting the next page of the list. If the number of results is greater than
	// [ListPrivateSubnetOperationsRequest.page_size], use `next_page_token` as the value
	// for the [ListPrivateSubnetOperationsRequest.page_token] parameter in the next list request.
	// Each subsequent page will have its own `next_page_token` to continue paging through the results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateSubnetOperationsResponse) Reset() {
	*x = ListPrivateSubnetOperationsResponse{}
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateSubnetOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateSubnetOperationsResponse) ProtoMessage() {}

func (x *ListPrivateSubnetOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateSubnetOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListPrivateSubnetOperationsResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListPrivateSubnetOperationsResponse) GetOperations() []*operation.Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListPrivateSubnetOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_yandex_cloud_baremetal_v2_private_subnet_service_proto protoreflect.FileDescriptor

const file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDesc = "" +
	"\n" +
	"6yandex/cloud/baremetal/v2/private_subnet_service.proto\x12\x19yandex.cloud.baremetal.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a google/protobuf/field_mask.proto\x1a yandex/cloud/api/operation.proto\x1a.yandex/cloud/baremetal/v2/private_subnet.proto\x1a&yandex/cloud/operation/operation.proto\x1a\x1dyandex/cloud/validation.proto\"\x8c\x01\n" +
	"\x17GetPrivateSubnetRequest\x12\x1e\n" +
	"\bcloud_id\x18\x01 \x01(\tB\x03\xe0A\x02R\acloudId\x12 \n" +
	"\tfolder_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bfolderId\x12/\n" +
	"\x11private_subnet_id\x18\x03 \x01(\tB\x03\xe0A\x02R\x0fprivateSubnetId\"\xea\x01\n" +
	"\x19ListPrivateSubnetsRequest\x12\x1e\n" +
	"\bcloud_id\x18\x01 \x01(\tB\x03\xe0A\x02R\acloudId\x12 \n" +
	"\tfolder_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bfolderId\x12*\n" +
	"\tpage_size\x18\x03 \x01(\x03B\r\xe0A\x01\xfa\xc71\x06<=1000R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tB\x03\xe0A\x01R\aorderBy\x12\x1b\n" +
	"\x06filter\x18\x06 \x01(\tB\x03\xe0A\x01R\x06filter\"\x97\x01\n" +
	"\x1aListPrivateSubnetsResponse\x12Q\n" +
	"\x0fprivate_subnets\x18\x01 \x03(\v2(.yandex.cloud.baremetal.v2.PrivateSubnetR\x0eprivateSubnets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb4\x01\n" +
	"\x1aCreatePrivateSubnetRequest\x12\x1e\n" +
	"\bcloud_id\x18\x01 \x01(\tB\x03\xe0A\x02R\acloudId\x12 \n" +
	"\tfolder_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bfolderId\x12T\n" +
	"\x0eprivate_subnet\x18\x03 \x01(\v2(.yandex.cloud.baremetal.v2.PrivateSubnetB\x03\xe0A\x02R\rprivateSubnet\"I\n" +
	"\x1bCreatePrivateSubnetMetadata\x12*\n" +
	"\x11private_subnet_id\x18\x01 \x01(\tR\x0fprivateSubnetId\"\xb4\x01\n" +
	"\x1aUpdatePrivateSubnetRequest\x12T\n" +
	"\x0eprivate_subnet\x18\x01 \x01(\v2(.yandex.cloud.baremetal.v2.PrivateSubnetB\x03\xe0A\x02R\rprivateSubnet\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"I\n" +
	"\x1bUpdatePrivateSubnetMetadata\x12*\n" +
	"\x11private_subnet_id\x18\x01 \x01(\tR\x0fprivateSubnetId\"\x8f\x01\n" +
	"\x1aDeletePrivateSubnetRequest\x12\x1e\n" +
	"\bcloud_id\x18\x01 \x01(\tB\x03\xe0A\x02R\acloudId\x12 \n" +
	"\tfolder_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bfolderId\x12/\n" +
	"\x11private_subnet_id\x18\x03 \x01(\tB\x03\xe0A\x02R\x0fprivateSubnetId\"I\n" +
	"\x1bDeletePrivateSubnetMetadata\x12*\n" +
	"\x11private_subnet_id\x18\x01 \x01(\tR\x0fprivateSubnetId\"\xe7\x01\n" +
	"\"ListPrivateSubnetOperationsRequest\x12\x1e\n" +
	"\bcloud_id\x18\x01 \x01(\tB\x03\xe0A\x02R\acloudId\x12 \n" +
	"\tfolder_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bfolderId\x12/\n" +
	"\x11private_subnet_id\x18\x03 \x01(\tB\x03\xe0A\x02R\x0fprivateSubnetId\x12*\n" +
	"\tpage_size\x18\x04 \x01(\x03B\r\xe0A\x01\xfa\xc71\x06<=1000R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tB\x03\xe0A\x01R\tpageToken\"\x90\x01\n" +
	"#ListPrivateSubnetOperationsResponse\x12A\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2!.yandex.cloud.operation.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xd3\r\n" +
	"\x14PrivateSubnetService\x12\xf8\x01\n" +
	"\x10GetPrivateSubnet\x122.yandex.cloud.baremetal.v2.GetPrivateSubnetRequest\x1a(.yandex.cloud.baremetal.v2.PrivateSubnet\"\x85\x01\xdaA$cloud_id,folder_id,private_subnet_id\x82\xd3\xe4\x93\x02X\x12V/baremetal/v2/clouds/{cloud_id}/folders/{folder_id}/privateSubnets/{private_subnet_id}\x12\xe2\x01\n" +
	"\x12ListPrivateSubnets\x124.yandex.cloud.baremetal.v2.ListPrivateSubnetsRequest\x1a5.yandex.cloud.baremetal.v2.ListPrivateSubnetsResponse\"_\xdaA\x12cloud_id,folder_id\x82\xd3\xe4\x93\x02D\x12B/baremetal/v2/clouds/{cloud_id}/folders/{folder_id}/privateSubnets\x12\x93\x02\n" +
	"\x13CreatePrivateSubnet\x125.yandex.cloud.baremetal.v2.CreatePrivateSubnetRequest\x1a!.yandex.cloud.operation.Operation\"\xa1\x01\xdaA!cloud_id,folder_id,private_subnet\xb2\xd2*,\n" +
	"\x1bCreatePrivateSubnetMetadata\x12\rPrivateSubnet\x82\xd3\xe4\x93\x02G:\x01*\"B/baremetal/v2/clouds/{cloud_id}/folders/{folder_id}/privateSubnets\x12\xdc\x02\n" +
	"\x13UpdatePrivateSubnet\x125.yandex.cloud.baremetal.v2.UpdatePrivateSubnetRequest\x1a!.yandex.cloud.operation.Operation\"\xea\x01\xdaA\x1aprivate_subnet,update_mask\xb2\xd2*,\n" +
	"\x1bUpdatePrivateSubnetMetadata\x12\rPrivateSubnet\x82\xd3\xe4\x93\x02\x96\x01:\x0eprivate_subnet2\x83\x01/baremetal/v2/clouds/{private_subnet.cloud_id}/folders/{private_subnet.folder_id}/privateSubnets/{private_subnet.private_subnet_id}\x12\xaf\x02\n" +
	"\x13DeletePrivateSubnet\x125.yandex.cloud.baremetal.v2.DeletePrivateSubnetRequest\x1a!.yandex.cloud.operation.Operation\"\xbd\x01\xdaA$cloud_id,folder_id,private_subnet_id\xb2\xd2*4\n" +
	"\x1bDeletePrivateSubnetMetadata\x12\x15google.protobuf.Empty\x82\xd3\xe4\x93\x02X*V/baremetal/v2/clouds/{cloud_id}/folders/{folder_id}/privateSubnets/{private_subnet_id}\x12\xb3\x02\n" +
	"\x1bListPrivateSubnetOperations\x12=.yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsRequest\x1a>.yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsResponse\"\x94\x01\xdaA$cloud_id,folder_id,private_subnet_id\x82\xd3\xe4\x93\x02g\x12e/baremetal/v2/clouds/{cloud_id}/folders/{folder_id}/privateSubnets/{private_subnet_id}:listOperationsBl\n" +
	"!yandex.cloud.api.api.baremetal.v2ZGgithub.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2;baremetalb\x06proto3"

var (
	file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescOnce sync.Once
	file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescData []byte
)

func file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescGZIP() []byte {
	file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDesc), len(file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDesc)))
	})
	return file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDescData
}

var file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_yandex_cloud_baremetal_v2_private_subnet_service_proto_goTypes = []any{
	(*GetPrivateSubnetRequest)(nil),             // 0: yandex.cloud.baremetal.v2.GetPrivateSubnetRequest
	(*ListPrivateSubnetsRequest)(nil),           // 1: yandex.cloud.baremetal.v2.ListPrivateSubnetsRequest
	(*ListPrivateSubnetsResponse)(nil),          // 2: yandex.cloud.baremetal.v2.ListPrivateSubnetsResponse
	(*CreatePrivateSubnetRequest)(nil),          // 3: yandex.cloud.baremetal.v2.CreatePrivateSubnetRequest
	(*CreatePrivateSubnetMetadata)(nil),         // 4: yandex.cloud.baremetal.v2.CreatePrivateSubnetMetadata
	(*UpdatePrivateSubnetRequest)(nil),          // 5: yandex.cloud.baremetal.v2.UpdatePrivateSubnetRequest
	(*UpdatePrivateSubnetMetadata)(nil),         // 6: yandex.cloud.baremetal.v2.UpdatePrivateSubnetMetadata
	(*DeletePrivateSubnetRequest)(nil),          // 7: yandex.cloud.baremetal.v2.DeletePrivateSubnetRequest
	(*DeletePrivateSubnetMetadata)(nil),         // 8: yandex.cloud.baremetal.v2.DeletePrivateSubnetMetadata
	(*ListPrivateSubnetOperationsRequest)(nil),  // 9: yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsRequest
	(*ListPrivateSubnetOperationsResponse)(nil), // 10: yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsResponse
	(*PrivateSubnet)(nil),                       // 11: yandex.cloud.baremetal.v2.PrivateSubnet
	(*fieldmaskpb.FieldMask)(nil),               // 12: google.protobuf.FieldMask
	(*operation.Operation)(nil),                 // 13: yandex.cloud.operation.Operation
}
var file_yandex_cloud_baremetal_v2_private_subnet_service_proto_depIdxs = []int32{
	11, // 0: yandex.cloud.baremetal.v2.ListPrivateSubnetsResponse.private_subnets:type_name -> yandex.cloud.baremetal.v2.PrivateSubnet
	11, // 1: yandex.cloud.baremetal.v2.CreatePrivateSubnetRequest.private_subnet:type_name -> yandex.cloud.baremetal.v2.PrivateSubnet
	11, // 2: yandex.cloud.baremetal.v2.UpdatePrivateSubnetRequest.private_subnet:type_name -> yandex.cloud.baremetal.v2.PrivateSubnet
	12, // 3: yandex.cloud.baremetal.v2.UpdatePrivateSubnetRequest.update_mask:type_name -> google.protobuf.FieldMask
	13, // 4: yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsResponse.operations:type_name -> yandex.cloud.operation.Operation
	0,  // 5: yandex.cloud.baremetal.v2.PrivateSubnetService.GetPrivateSubnet:input_type -> yandex.cloud.baremetal.v2.GetPrivateSubnetRequest
	1,  // 6: yandex.cloud.baremetal.v2.PrivateSubnetService.ListPrivateSubnets:input_type -> yandex.cloud.baremetal.v2.ListPrivateSubnetsRequest
	3,  // 7: yandex.cloud.baremetal.v2.PrivateSubnetService.CreatePrivateSubnet:input_type -> yandex.cloud.baremetal.v2.CreatePrivateSubnetRequest
	5,  // 8: yandex.cloud.baremetal.v2.PrivateSubnetService.UpdatePrivateSubnet:input_type -> yandex.cloud.baremetal.v2.UpdatePrivateSubnetRequest
	7,  // 9: yandex.cloud.baremetal.v2.PrivateSubnetService.DeletePrivateSubnet:input_type -> yandex.cloud.baremetal.v2.DeletePrivateSubnetRequest
	9,  // 10: yandex.cloud.baremetal.v2.PrivateSubnetService.ListPrivateSubnetOperations:input_type -> yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsRequest
	11, // 11: yandex.cloud.baremetal.v2.PrivateSubnetService.GetPrivateSubnet:output_type -> yandex.cloud.baremetal.v2.PrivateSubnet
	2,  // 12: yandex.cloud.baremetal.v2.PrivateSubnetService.ListPrivateSubnets:output_type -> yandex.cloud.baremetal.v2.ListPrivateSubnetsResponse
	13, // 13: yandex.cloud.baremetal.v2.PrivateSubnetService.CreatePrivateSubnet:output_type -> yandex.cloud.operation.Operation
	13, // 14: yandex.cloud.baremetal.v2.PrivateSubnetService.UpdatePrivateSubnet:output_type -> yandex.cloud.operation.Operation
	13, // 15: yandex.cloud.baremetal.v2.PrivateSubnetService.DeletePrivateSubnet:output_type -> yandex.cloud.operation.Operation
	10, // 16: yandex.cloud.baremetal.v2.PrivateSubnetService.ListPrivateSubnetOperations:output_type -> yandex.cloud.baremetal.v2.ListPrivateSubnetOperationsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_yandex_cloud_baremetal_v2_private_subnet_service_proto_init() }
func file_yandex_cloud_baremetal_v2_private_subnet_service_proto_init() {
	if File_yandex_cloud_baremetal_v2_private_subnet_service_proto != nil {
		return
	}
	file_yandex_cloud_baremetal_v2_private_subnet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDesc), len(file_yandex_cloud_baremetal_v2_private_subnet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yandex_cloud_baremetal_v2_private_subnet_service_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_baremetal_v2_private_subnet_service_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_baremetal_v2_private_subnet_service_proto_msgTypes,
	}.Build()
	File_yandex_cloud_baremetal_v2_private_subnet_service_proto = out.File
	file_yandex_cloud_baremetal_v2_private_subnet_service_proto_goTypes = nil
	file_yandex_cloud_baremetal_v2_private_subnet_service_proto_depIdxs = nil
}
