// Code generated by protoc-gen-goext. DO NOT EDIT.

package baremetal

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type Server_Configuration = isServer_Configuration

func (m *Server) SetConfiguration(v Server_Configuration) {
	m.Configuration = v
}

func (m *Server) SetServerId(v string) {
	m.ServerId = v
}

func (m *Server) SetCloudId(v string) {
	m.CloudId = v
}

func (m *Server) SetFolderId(v string) {
	m.FolderId = v
}

func (m *Server) SetName(v string) {
	m.Name = v
}

func (m *Server) SetDescription(v string) {
	m.Description = v
}

func (m *Server) SetHardwarePoolId(v string) {
	m.HardwarePoolId = v
}

func (m *Server) SetState(v Server_State) {
	m.State = v
}

func (m *Server) SetOsSettings(v *OsSettings) {
	m.OsSettings = v
}

func (m *Server) SetRentalPeriodStartTime(v *timestamppb.Timestamp) {
	m.RentalPeriodStartTime = v
}

func (m *Server) SetRentalPeriodId(v string) {
	m.RentalPeriodId = v
}

func (m *Server) SetNextRentalPeriodId(v string) {
	m.NextRentalPeriodId = v
}

func (m *Server) SetRentalPeriodEndTime(v *timestamppb.Timestamp) {
	m.RentalPeriodEndTime = v
}

func (m *Server) SetNetworkInterfaces(v []*NetworkInterface) {
	m.NetworkInterfaces = v
}

func (m *Server) SetProlongationState(v Server_ProlongationState) {
	m.ProlongationState = v
}

func (m *Server) SetDisks(v []*Disk) {
	m.Disks = v
}

func (m *Server) SetCustomConfiguration(v *UserConfiguration) {
	m.Configuration = &Server_CustomConfiguration{
		CustomConfiguration: v,
	}
}

func (m *Server) SetStockConfigurationId(v string) {
	m.Configuration = &Server_StockConfigurationId{
		StockConfigurationId: v,
	}
}

func (m *Server) SetCreateTime(v *timestamppb.Timestamp) {
	m.CreateTime = v
}

func (m *Server) SetUpdateTime(v *timestamppb.Timestamp) {
	m.UpdateTime = v
}

func (m *Server) SetAnnotations(v map[string]string) {
	m.Annotations = v
}

type NetworkInterface_Interface = isNetworkInterface_Interface

func (m *NetworkInterface) SetInterface(v NetworkInterface_Interface) {
	m.Interface = v
}

func (m *NetworkInterface) SetNetworkInterfaceId(v string) {
	m.NetworkInterfaceId = v
}

func (m *NetworkInterface) SetMacAddress(v string) {
	m.MacAddress = v
}

func (m *NetworkInterface) SetPrivateInterface(v *PrivateNetworkInterface) {
	m.Interface = &NetworkInterface_PrivateInterface{
		PrivateInterface: v,
	}
}

func (m *NetworkInterface) SetPublicInterface(v *PublicNetworkInterface) {
	m.Interface = &NetworkInterface_PublicInterface{
		PublicInterface: v,
	}
}

func (m *NetworkInterface) SetConfigurationNetworkInterfaceId(v string) {
	m.ConfigurationNetworkInterfaceId = v
}

func (m *PrivateNetworkInterface) SetNativeSubnetId(v string) {
	m.NativeSubnetId = v
}

func (m *PrivateNetworkInterface) SetIpAddress(v string) {
	m.IpAddress = v
}

func (m *PrivateNetworkInterface) SetMacLimit(v int64) {
	m.MacLimit = v
}

func (m *PrivateNetworkInterface) SetVlanSubinterfaces(v []*VLANSubinterface) {
	m.VlanSubinterfaces = v
}

func (m *VLANSubinterface) SetTaggedSubnetId(v string) {
	m.TaggedSubnetId = v
}

func (m *VLANSubinterface) SetIpAddress(v string) {
	m.IpAddress = v
}

func (m *VLANSubinterface) SetMacLimit(v int64) {
	m.MacLimit = v
}

type PublicNetworkInterface_NativeSubnetConfig = isPublicNetworkInterface_NativeSubnetConfig

func (m *PublicNetworkInterface) SetNativeSubnetConfig(v PublicNetworkInterface_NativeSubnetConfig) {
	m.NativeSubnetConfig = v
}

func (m *PublicNetworkInterface) SetIpAddress(v string) {
	m.IpAddress = v
}

func (m *PublicNetworkInterface) SetNativeSubnetId(v string) {
	m.NativeSubnetId = v
}

func (m *PublicNetworkInterface) SetMacLimit(v int64) {
	m.MacLimit = v
}

func (m *PublicNetworkInterface) SetInternetTrafficPlan(v InternetTrafficPlan) {
	m.InternetTrafficPlan = v
}

func (m *PublicNetworkInterface) SetNativeSubnet(v *PublicNetworkInterface_NativeSubnet) {
	m.NativeSubnetConfig = &PublicNetworkInterface_NativeSubnet_{
		NativeSubnet: v,
	}
}

func (m *PublicNetworkInterface) SetNewNativeSubnet(v *PublicNetworkInterface_NewNativeSubnet) {
	m.NativeSubnetConfig = &PublicNetworkInterface_NewNativeSubnet_{
		NewNativeSubnet: v,
	}
}

func (m *PublicNetworkInterface_NativeSubnet) SetSubnetId(v string) {
	m.SubnetId = v
}

func (m *PublicNetworkInterface_NewNativeSubnet) SetAddressingType(v PublicNetworkInterface_NewNativeSubnet_AddressingType) {
	m.AddressingType = v
}

type OsSettings_SshKey = isOsSettings_SshKey

func (m *OsSettings) SetSshKey(v OsSettings_SshKey) {
	m.SshKey = v
}

type OsSettings_Password = isOsSettings_Password

func (m *OsSettings) SetPassword(v OsSettings_Password) {
	m.Password = v
}

func (m *OsSettings) SetImageId(v string) {
	m.ImageId = v
}

func (m *OsSettings) SetSshPublicKey(v string) {
	m.SshPublicKey = v
}

func (m *OsSettings) SetSshPublicKeyText(v string) {
	m.SshKey = &OsSettings_SshPublicKeyText{
		SshPublicKeyText: v,
	}
}

func (m *OsSettings) SetUserSshId(v string) {
	m.SshKey = &OsSettings_UserSshId{
		UserSshId: v,
	}
}

func (m *OsSettings) SetPasswordPlainText(v string) {
	m.Password = &OsSettings_PasswordPlainText{
		PasswordPlainText: v,
	}
}

func (m *OsSettings) SetPasswordLockboxSecret(v *LockboxSecret) {
	m.Password = &OsSettings_PasswordLockboxSecret{
		PasswordLockboxSecret: v,
	}
}

func (m *OsSettings) SetStorages(v []*Storage) {
	m.Storages = v
}

func (m *LockboxSecret) SetSecretId(v string) {
	m.SecretId = v
}

func (m *LockboxSecret) SetVersionId(v string) {
	m.VersionId = v
}

func (m *LockboxSecret) SetKey(v string) {
	m.Key = v
}
