// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: yandex/cloud/baremetal/v2/extend/stackland_cluster.proto

package baremetal

import (
	_ "github.com/yandex-cloud/go-genproto/yandex/cloud"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StacklandCluster_State int32

const (
	// Unspecified state.
	StacklandCluster_STATE_UNSPECIFIED StacklandCluster_State = 0
	// Cluster is being created.
	StacklandCluster_CREATING StacklandCluster_State = 1
	// Cluster is being updated.
	StacklandCluster_UPDATING StacklandCluster_State = 2
	// Cluster is running.
	StacklandCluster_RUNNING StacklandCluster_State = 3
	// Cluster is being deleted.
	StacklandCluster_DELETING StacklandCluster_State = 4
	// Cluster is in error state.
	StacklandCluster_ERROR StacklandCluster_State = 5
)

// Enum value maps for StacklandCluster_State.
var (
	StacklandCluster_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "CREATING",
		2: "UPDATING",
		3: "RUNNING",
		4: "DELETING",
		5: "ERROR",
	}
	StacklandCluster_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"CREATING":          1,
		"UPDATING":          2,
		"RUNNING":           3,
		"DELETING":          4,
		"ERROR":             5,
	}
)

func (x StacklandCluster_State) Enum() *StacklandCluster_State {
	p := new(StacklandCluster_State)
	*p = x
	return p
}

func (x StacklandCluster_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StacklandCluster_State) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes[0].Descriptor()
}

func (StacklandCluster_State) Type() protoreflect.EnumType {
	return &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes[0]
}

func (x StacklandCluster_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StacklandCluster_State.Descriptor instead.
func (StacklandCluster_State) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP(), []int{0, 0}
}

type StacklandCluster_StacklandPreset int32

const (
	// Unspecified preset.
	StacklandCluster_STACKLAND_PRESET_UNSPECIFIED StacklandCluster_StacklandPreset = 0
	// Minimal preset.
	StacklandCluster_MINIMAL StacklandCluster_StacklandPreset = 1
	// Full preset.
	StacklandCluster_FULL StacklandCluster_StacklandPreset = 2
)

// Enum value maps for StacklandCluster_StacklandPreset.
var (
	StacklandCluster_StacklandPreset_name = map[int32]string{
		0: "STACKLAND_PRESET_UNSPECIFIED",
		1: "MINIMAL",
		2: "FULL",
	}
	StacklandCluster_StacklandPreset_value = map[string]int32{
		"STACKLAND_PRESET_UNSPECIFIED": 0,
		"MINIMAL":                      1,
		"FULL":                         2,
	}
)

func (x StacklandCluster_StacklandPreset) Enum() *StacklandCluster_StacklandPreset {
	p := new(StacklandCluster_StacklandPreset)
	*p = x
	return p
}

func (x StacklandCluster_StacklandPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StacklandCluster_StacklandPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes[1].Descriptor()
}

func (StacklandCluster_StacklandPreset) Type() protoreflect.EnumType {
	return &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes[1]
}

func (x StacklandCluster_StacklandPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StacklandCluster_StacklandPreset.Descriptor instead.
func (StacklandCluster_StacklandPreset) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP(), []int{0, 1}
}

type StacklandCluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the cluster.
	StacklandClusterId string `protobuf:"bytes,1,opt,name=stackland_cluster_id,json=stacklandClusterId,proto3" json:"stackland_cluster_id,omitempty"`
	// ID of the cloud that the cluster belongs to.
	CloudId string `protobuf:"bytes,2,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	// ID of the folder that the cluster belongs to.
	FolderId string `protobuf:"bytes,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// Name of the cluster.
	// The display name is unique within the folder.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the server.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// State of the cluster.
	State StacklandCluster_State `protobuf:"varint,6,opt,name=state,proto3,enum=yandex.cloud.baremetal.v2.extend.StacklandCluster_State" json:"state,omitempty"`
	// Creation timestamp.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Update timestamp.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Resource labels as `key:value` pairs.
	Annotations map[string]string `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ID of the hardware pool that the cluster belongs to.
	HardwarePoolId string `protobuf:"bytes,10,opt,name=hardware_pool_id,json=hardwarePoolId,proto3" json:"hardware_pool_id,omitempty"`
	// Preset of the cluster.
	Preset StacklandCluster_StacklandPreset `protobuf:"varint,11,opt,name=preset,proto3,enum=yandex.cloud.baremetal.v2.extend.StacklandCluster_StacklandPreset" json:"preset,omitempty"`
	// Which node types are to be used for cluster roles.
	HostRoles *StacklandHostRoles `protobuf:"bytes,12,opt,name=host_roles,json=hostRoles,proto3" json:"host_roles,omitempty"`
	// Bastion node.
	BastionNode *Node `protobuf:"bytes,13,opt,name=bastion_node,json=bastionNode,proto3" json:"bastion_node,omitempty"`
	// ID of the subnet that the cluster belongs to.
	SubnetId string `protobuf:"bytes,14,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Optional CIDR to preselect in subnet.
	Cidr string `protobuf:"bytes,15,opt,name=cidr,proto3" json:"cidr,omitempty"`
	// Version of Stackland to be used.
	Version string `protobuf:"bytes,16,opt,name=version,proto3" json:"version,omitempty"`
	// License to activate Stackland.
	License string `protobuf:"bytes,17,opt,name=license,proto3" json:"license,omitempty"`
	// ID of secret with cluster credentials in lockbox.
	CredentialsLockboxSecretId string `protobuf:"bytes,18,opt,name=credentials_lockbox_secret_id,json=credentialsLockboxSecretId,proto3" json:"credentials_lockbox_secret_id,omitempty"`
	// URL in S3 to the cluster configuration.
	ConfigurationUrl string `protobuf:"bytes,19,opt,name=configuration_url,json=configurationUrl,proto3" json:"configuration_url,omitempty"`
	// IP of the cluster control plane. .
	VirtualIp string `protobuf:"bytes,21,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	// Base cluster DNS domain.
	ClusterDomain string `protobuf:"bytes,22,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"`
	// Cluster component URLs, available once the cluster is active.
	Subdomains *StacklandSubdomains `protobuf:"bytes,23,opt,name=subdomains,proto3" json:"subdomains,omitempty"`
	// Credentials for access to the bastion node.
	//
	// Input only field.
	BastionSpec   *BastionSpec `protobuf:"bytes,24,opt,name=bastion_spec,json=bastionSpec,proto3" json:"bastion_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StacklandCluster) Reset() {
	*x = StacklandCluster{}
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StacklandCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StacklandCluster) ProtoMessage() {}

func (x *StacklandCluster) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StacklandCluster.ProtoReflect.Descriptor instead.
func (*StacklandCluster) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *StacklandCluster) GetStacklandClusterId() string {
	if x != nil {
		return x.StacklandClusterId
	}
	return ""
}

func (x *StacklandCluster) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *StacklandCluster) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *StacklandCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StacklandCluster) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StacklandCluster) GetState() StacklandCluster_State {
	if x != nil {
		return x.State
	}
	return StacklandCluster_STATE_UNSPECIFIED
}

func (x *StacklandCluster) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StacklandCluster) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *StacklandCluster) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *StacklandCluster) GetHardwarePoolId() string {
	if x != nil {
		return x.HardwarePoolId
	}
	return ""
}

func (x *StacklandCluster) GetPreset() StacklandCluster_StacklandPreset {
	if x != nil {
		return x.Preset
	}
	return StacklandCluster_STACKLAND_PRESET_UNSPECIFIED
}

func (x *StacklandCluster) GetHostRoles() *StacklandHostRoles {
	if x != nil {
		return x.HostRoles
	}
	return nil
}

func (x *StacklandCluster) GetBastionNode() *Node {
	if x != nil {
		return x.BastionNode
	}
	return nil
}

func (x *StacklandCluster) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *StacklandCluster) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *StacklandCluster) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StacklandCluster) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *StacklandCluster) GetCredentialsLockboxSecretId() string {
	if x != nil {
		return x.CredentialsLockboxSecretId
	}
	return ""
}

func (x *StacklandCluster) GetConfigurationUrl() string {
	if x != nil {
		return x.ConfigurationUrl
	}
	return ""
}

func (x *StacklandCluster) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *StacklandCluster) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

func (x *StacklandCluster) GetSubdomains() *StacklandSubdomains {
	if x != nil {
		return x.Subdomains
	}
	return nil
}

func (x *StacklandCluster) GetBastionSpec() *BastionSpec {
	if x != nil {
		return x.BastionSpec
	}
	return nil
}

type StacklandHostRoles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node types used as controlplane nodes.
	Controlplane []*NodeGroup `protobuf:"bytes,1,rep,name=controlplane,proto3" json:"controlplane,omitempty"`
	// Node types used as combined nodes.
	Combined []*NodeGroup `protobuf:"bytes,2,rep,name=combined,proto3" json:"combined,omitempty"`
	// Node types used as workder nodes.
	Worker        []*NodeGroup `protobuf:"bytes,3,rep,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StacklandHostRoles) Reset() {
	*x = StacklandHostRoles{}
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StacklandHostRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StacklandHostRoles) ProtoMessage() {}

func (x *StacklandHostRoles) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StacklandHostRoles.ProtoReflect.Descriptor instead.
func (*StacklandHostRoles) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *StacklandHostRoles) GetControlplane() []*NodeGroup {
	if x != nil {
		return x.Controlplane
	}
	return nil
}

func (x *StacklandHostRoles) GetCombined() []*NodeGroup {
	if x != nil {
		return x.Combined
	}
	return nil
}

func (x *StacklandHostRoles) GetWorker() []*NodeGroup {
	if x != nil {
		return x.Worker
	}
	return nil
}

type StacklandSubdomains struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster URL.
	Console string `protobuf:"bytes,1,opt,name=console,proto3" json:"console,omitempty"`
	// Cluster URL.
	Dashboard string `protobuf:"bytes,2,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	// Grafana URL.
	Grafana string `protobuf:"bytes,3,opt,name=grafana,proto3" json:"grafana,omitempty"`
	// Prometheus URL.
	Prometheus string `protobuf:"bytes,4,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	// Alertmanager URL.
	Alertmanager  string `protobuf:"bytes,5,opt,name=alertmanager,proto3" json:"alertmanager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StacklandSubdomains) Reset() {
	*x = StacklandSubdomains{}
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StacklandSubdomains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StacklandSubdomains) ProtoMessage() {}

func (x *StacklandSubdomains) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StacklandSubdomains.ProtoReflect.Descriptor instead.
func (*StacklandSubdomains) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *StacklandSubdomains) GetConsole() string {
	if x != nil {
		return x.Console
	}
	return ""
}

func (x *StacklandSubdomains) GetDashboard() string {
	if x != nil {
		return x.Dashboard
	}
	return ""
}

func (x *StacklandSubdomains) GetGrafana() string {
	if x != nil {
		return x.Grafana
	}
	return ""
}

func (x *StacklandSubdomains) GetPrometheus() string {
	if x != nil {
		return x.Prometheus
	}
	return ""
}

func (x *StacklandSubdomains) GetAlertmanager() string {
	if x != nil {
		return x.Alertmanager
	}
	return ""
}

var File_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto protoreflect.FileDescriptor

const file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDesc = "" +
	"\n" +
	"8yandex/cloud/baremetal/v2/extend/stackland_cluster.proto\x12 yandex.cloud.baremetal.v2.extend\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.yandex/cloud/baremetal/v2/extend/cluster.proto\x1a,yandex/cloud/baremetal/v2/extend/nodes.proto\x1a\x1dyandex/cloud/validation.proto\"\x85\r\n" +
	"\x10StacklandCluster\x128\n" +
	"\x14stackland_cluster_id\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\bR\x12stacklandClusterId\x12!\n" +
	"\bcloud_id\x18\x02 \x01(\tB\x06\xe0A\x02\xe0A\x05R\acloudId\x12#\n" +
	"\tfolder_id\x18\x03 \x01(\tB\x06\xe0A\x02\xe0A\x05R\bfolderId\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tB\x03\xe0A\x01R\vdescription\x12S\n" +
	"\x05state\x18\x06 \x01(\x0e28.yandex.cloud.baremetal.v2.extend.StacklandCluster.StateB\x03\xe0A\x03R\x05state\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\xa5\x01\n" +
	"\vannotations\x18\t \x03(\v2C.yandex.cloud.baremetal.v2.extend.StacklandCluster.AnnotationsEntryB>\xe0A\x01\xf2\xc71\v[-_0-9a-z]*\x82\xc81\x04<=64\x8a\xc81\x04<=63\xb2\xc81\x18\x12\x10[a-z][-_0-9a-z]*\x1a\x041-63R\vannotations\x12-\n" +
	"\x10hardware_pool_id\x18\n" +
	" \x01(\tB\x03\xe0A\x02R\x0ehardwarePoolId\x12_\n" +
	"\x06preset\x18\v \x01(\x0e2B.yandex.cloud.baremetal.v2.extend.StacklandCluster.StacklandPresetB\x03\xe0A\x01R\x06preset\x12X\n" +
	"\n" +
	"host_roles\x18\f \x01(\v24.yandex.cloud.baremetal.v2.extend.StacklandHostRolesB\x03\xe0A\x02R\thostRoles\x12N\n" +
	"\fbastion_node\x18\r \x01(\v2&.yandex.cloud.baremetal.v2.extend.NodeB\x03\xe0A\x02R\vbastionNode\x12#\n" +
	"\tsubnet_id\x18\x0e \x01(\tB\x06\xe0A\x03\xe0A\x01R\bsubnetId\x12\x1a\n" +
	"\x04cidr\x18\x0f \x01(\tB\x06\xe0A\x01\xe0A\x04R\x04cidr\x12\x1d\n" +
	"\aversion\x18\x10 \x01(\tB\x03\xe0A\x02R\aversion\x12 \n" +
	"\alicense\x18\x11 \x01(\tB\x06\xe0A\x02\xe0A\x04R\alicense\x12F\n" +
	"\x1dcredentials_lockbox_secret_id\x18\x12 \x01(\tB\x03\xe0A\x03R\x1acredentialsLockboxSecretId\x120\n" +
	"\x11configuration_url\x18\x13 \x01(\tB\x03\xe0A\x03R\x10configurationUrl\x12\"\n" +
	"\n" +
	"virtual_ip\x18\x15 \x01(\tB\x03\xe0A\x03R\tvirtualIp\x12*\n" +
	"\x0ecluster_domain\x18\x16 \x01(\tB\x03\xe0A\x01R\rclusterDomain\x12Z\n" +
	"\n" +
	"subdomains\x18\x17 \x01(\v25.yandex.cloud.baremetal.v2.extend.StacklandSubdomainsB\x03\xe0A\x03R\n" +
	"subdomains\x12X\n" +
	"\fbastion_spec\x18\x18 \x01(\v2-.yandex.cloud.baremetal.v2.extend.BastionSpecB\x06\xe0A\x02\xe0A\x04R\vbastionSpec\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\f\n" +
	"\bUPDATING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\f\n" +
	"\bDELETING\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x05\"J\n" +
	"\x0fStacklandPreset\x12 \n" +
	"\x1cSTACKLAND_PRESET_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMINIMAL\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02J\x04\b\x14\x10\x15\"\x82\x02\n" +
	"\x12StacklandHostRoles\x12T\n" +
	"\fcontrolplane\x18\x01 \x03(\v2+.yandex.cloud.baremetal.v2.extend.NodeGroupB\x03\xe0A\x01R\fcontrolplane\x12L\n" +
	"\bcombined\x18\x02 \x03(\v2+.yandex.cloud.baremetal.v2.extend.NodeGroupB\x03\xe0A\x01R\bcombined\x12H\n" +
	"\x06worker\x18\x03 \x03(\v2+.yandex.cloud.baremetal.v2.extend.NodeGroupB\x03\xe0A\x01R\x06worker\"\xc4\x01\n" +
	"\x13StacklandSubdomains\x12\x1d\n" +
	"\aconsole\x18\x01 \x01(\tB\x03\xe0A\x03R\aconsole\x12!\n" +
	"\tdashboard\x18\x02 \x01(\tB\x03\xe0A\x03R\tdashboard\x12\x1d\n" +
	"\agrafana\x18\x03 \x01(\tB\x03\xe0A\x03R\agrafana\x12#\n" +
	"\n" +
	"prometheus\x18\x04 \x01(\tB\x03\xe0A\x03R\n" +
	"prometheus\x12'\n" +
	"\falertmanager\x18\x05 \x01(\tB\x03\xe0A\x03R\falertmanagerBz\n" +
	"(yandex.cloud.api.api.baremetal.v2.extendZNgithub.com/yandex-cloud/go-genproto/yandex/cloud/baremetal/v2/extend;baremetalb\x06proto3"

var (
	file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescOnce sync.Once
	file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescData []byte
)

func file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescGZIP() []byte {
	file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDesc), len(file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDesc)))
	})
	return file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDescData
}

var file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_goTypes = []any{
	(StacklandCluster_State)(0),           // 0: yandex.cloud.baremetal.v2.extend.StacklandCluster.State
	(StacklandCluster_StacklandPreset)(0), // 1: yandex.cloud.baremetal.v2.extend.StacklandCluster.StacklandPreset
	(*StacklandCluster)(nil),              // 2: yandex.cloud.baremetal.v2.extend.StacklandCluster
	(*StacklandHostRoles)(nil),            // 3: yandex.cloud.baremetal.v2.extend.StacklandHostRoles
	(*StacklandSubdomains)(nil),           // 4: yandex.cloud.baremetal.v2.extend.StacklandSubdomains
	nil,                                   // 5: yandex.cloud.baremetal.v2.extend.StacklandCluster.AnnotationsEntry
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*Node)(nil),                          // 7: yandex.cloud.baremetal.v2.extend.Node
	(*BastionSpec)(nil),                   // 8: yandex.cloud.baremetal.v2.extend.BastionSpec
	(*NodeGroup)(nil),                     // 9: yandex.cloud.baremetal.v2.extend.NodeGroup
}
var file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_depIdxs = []int32{
	0,  // 0: yandex.cloud.baremetal.v2.extend.StacklandCluster.state:type_name -> yandex.cloud.baremetal.v2.extend.StacklandCluster.State
	6,  // 1: yandex.cloud.baremetal.v2.extend.StacklandCluster.create_time:type_name -> google.protobuf.Timestamp
	6,  // 2: yandex.cloud.baremetal.v2.extend.StacklandCluster.update_time:type_name -> google.protobuf.Timestamp
	5,  // 3: yandex.cloud.baremetal.v2.extend.StacklandCluster.annotations:type_name -> yandex.cloud.baremetal.v2.extend.StacklandCluster.AnnotationsEntry
	1,  // 4: yandex.cloud.baremetal.v2.extend.StacklandCluster.preset:type_name -> yandex.cloud.baremetal.v2.extend.StacklandCluster.StacklandPreset
	3,  // 5: yandex.cloud.baremetal.v2.extend.StacklandCluster.host_roles:type_name -> yandex.cloud.baremetal.v2.extend.StacklandHostRoles
	7,  // 6: yandex.cloud.baremetal.v2.extend.StacklandCluster.bastion_node:type_name -> yandex.cloud.baremetal.v2.extend.Node
	4,  // 7: yandex.cloud.baremetal.v2.extend.StacklandCluster.subdomains:type_name -> yandex.cloud.baremetal.v2.extend.StacklandSubdomains
	8,  // 8: yandex.cloud.baremetal.v2.extend.StacklandCluster.bastion_spec:type_name -> yandex.cloud.baremetal.v2.extend.BastionSpec
	9,  // 9: yandex.cloud.baremetal.v2.extend.StacklandHostRoles.controlplane:type_name -> yandex.cloud.baremetal.v2.extend.NodeGroup
	9,  // 10: yandex.cloud.baremetal.v2.extend.StacklandHostRoles.combined:type_name -> yandex.cloud.baremetal.v2.extend.NodeGroup
	9,  // 11: yandex.cloud.baremetal.v2.extend.StacklandHostRoles.worker:type_name -> yandex.cloud.baremetal.v2.extend.NodeGroup
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_init() }
func file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_init() {
	if File_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto != nil {
		return
	}
	file_yandex_cloud_baremetal_v2_extend_cluster_proto_init()
	file_yandex_cloud_baremetal_v2_extend_nodes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDesc), len(file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_msgTypes,
	}.Build()
	File_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto = out.File
	file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_goTypes = nil
	file_yandex_cloud_baremetal_v2_extend_stackland_cluster_proto_depIdxs = nil
}
