// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: yandex/cloud/loadtesting/api/v1/common/quantiles.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quantiles (percentiles).
type QuantileType int32

const (
	// Unspecified percentile.
	QuantileType_QUANTILE_TYPE_UNSPECIFIED QuantileType = 0
	// 50 percentile (median).
	QuantileType_QUANTILE_TYPE_50 QuantileType = 1
	// 75 percentile.
	QuantileType_QUANTILE_TYPE_75 QuantileType = 2
	// 80 percentile.
	QuantileType_QUANTILE_TYPE_80 QuantileType = 3
	// 85 percentile.
	QuantileType_QUANTILE_TYPE_85 QuantileType = 4
	// 90 percentile.
	QuantileType_QUANTILE_TYPE_90 QuantileType = 5
	// 95 percentile.
	QuantileType_QUANTILE_TYPE_95 QuantileType = 6
	// 98 percentile.
	QuantileType_QUANTILE_TYPE_98 QuantileType = 7
	// 99 percentile.
	QuantileType_QUANTILE_TYPE_99 QuantileType = 8
	// 100 percentile (maximum or minimum).
	QuantileType_QUANTILE_TYPE_100 QuantileType = 9
)

// Enum value maps for QuantileType.
var (
	QuantileType_name = map[int32]string{
		0: "QUANTILE_TYPE_UNSPECIFIED",
		1: "QUANTILE_TYPE_50",
		2: "QUANTILE_TYPE_75",
		3: "QUANTILE_TYPE_80",
		4: "QUANTILE_TYPE_85",
		5: "QUANTILE_TYPE_90",
		6: "QUANTILE_TYPE_95",
		7: "QUANTILE_TYPE_98",
		8: "QUANTILE_TYPE_99",
		9: "QUANTILE_TYPE_100",
	}
	QuantileType_value = map[string]int32{
		"QUANTILE_TYPE_UNSPECIFIED": 0,
		"QUANTILE_TYPE_50":          1,
		"QUANTILE_TYPE_75":          2,
		"QUANTILE_TYPE_80":          3,
		"QUANTILE_TYPE_85":          4,
		"QUANTILE_TYPE_90":          5,
		"QUANTILE_TYPE_95":          6,
		"QUANTILE_TYPE_98":          7,
		"QUANTILE_TYPE_99":          8,
		"QUANTILE_TYPE_100":         9,
	}
)

func (x QuantileType) Enum() *QuantileType {
	p := new(QuantileType)
	*p = x
	return p
}

func (x QuantileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuantileType) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_enumTypes[0].Descriptor()
}

func (QuantileType) Type() protoreflect.EnumType {
	return &file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_enumTypes[0]
}

func (x QuantileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuantileType.Descriptor instead.
func (QuantileType) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescGZIP(), []int{0}
}

// Statistical data aggregated by predefined set of quantiles.
type Quantiles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 50 percentile (median).
	Q50 float64 `protobuf:"fixed64,1,opt,name=q50,proto3" json:"q50,omitempty"`
	// 75 percentile.
	Q75 float64 `protobuf:"fixed64,2,opt,name=q75,proto3" json:"q75,omitempty"`
	// 80 percentile.
	Q80 float64 `protobuf:"fixed64,3,opt,name=q80,proto3" json:"q80,omitempty"`
	// 85 percentile.
	Q85 float64 `protobuf:"fixed64,4,opt,name=q85,proto3" json:"q85,omitempty"`
	// 90 percentile.
	Q90 float64 `protobuf:"fixed64,5,opt,name=q90,proto3" json:"q90,omitempty"`
	// 95 percentile.
	Q95 float64 `protobuf:"fixed64,6,opt,name=q95,proto3" json:"q95,omitempty"`
	// 98 percentile.
	Q98 float64 `protobuf:"fixed64,7,opt,name=q98,proto3" json:"q98,omitempty"`
	// 99 percentile.
	Q99 float64 `protobuf:"fixed64,8,opt,name=q99,proto3" json:"q99,omitempty"`
	// 100 percentile (maximum or minimum).
	Q100          float64 `protobuf:"fixed64,9,opt,name=q100,proto3" json:"q100,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quantiles) Reset() {
	*x = Quantiles{}
	mi := &file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quantiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantiles) ProtoMessage() {}

func (x *Quantiles) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantiles.ProtoReflect.Descriptor instead.
func (*Quantiles) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescGZIP(), []int{0}
}

func (x *Quantiles) GetQ50() float64 {
	if x != nil {
		return x.Q50
	}
	return 0
}

func (x *Quantiles) GetQ75() float64 {
	if x != nil {
		return x.Q75
	}
	return 0
}

func (x *Quantiles) GetQ80() float64 {
	if x != nil {
		return x.Q80
	}
	return 0
}

func (x *Quantiles) GetQ85() float64 {
	if x != nil {
		return x.Q85
	}
	return 0
}

func (x *Quantiles) GetQ90() float64 {
	if x != nil {
		return x.Q90
	}
	return 0
}

func (x *Quantiles) GetQ95() float64 {
	if x != nil {
		return x.Q95
	}
	return 0
}

func (x *Quantiles) GetQ98() float64 {
	if x != nil {
		return x.Q98
	}
	return 0
}

func (x *Quantiles) GetQ99() float64 {
	if x != nil {
		return x.Q99
	}
	return 0
}

func (x *Quantiles) GetQ100() float64 {
	if x != nil {
		return x.Q100
	}
	return 0
}

var File_yandex_cloud_loadtesting_api_v1_common_quantiles_proto protoreflect.FileDescriptor

const file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDesc = "" +
	"\n" +
	"6yandex/cloud/loadtesting/api/v1/common/quantiles.proto\x12&yandex.cloud.loadtesting.api.v1.common\"\xaf\x01\n" +
	"\tQuantiles\x12\x10\n" +
	"\x03q50\x18\x01 \x01(\x01R\x03q50\x12\x10\n" +
	"\x03q75\x18\x02 \x01(\x01R\x03q75\x12\x10\n" +
	"\x03q80\x18\x03 \x01(\x01R\x03q80\x12\x10\n" +
	"\x03q85\x18\x04 \x01(\x01R\x03q85\x12\x10\n" +
	"\x03q90\x18\x05 \x01(\x01R\x03q90\x12\x10\n" +
	"\x03q95\x18\x06 \x01(\x01R\x03q95\x12\x10\n" +
	"\x03q98\x18\a \x01(\x01R\x03q98\x12\x10\n" +
	"\x03q99\x18\b \x01(\x01R\x03q99\x12\x12\n" +
	"\x04q100\x18\t \x01(\x01R\x04q100*\xf4\x01\n" +
	"\fQuantileType\x12\x1d\n" +
	"\x19QUANTILE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10QUANTILE_TYPE_50\x10\x01\x12\x14\n" +
	"\x10QUANTILE_TYPE_75\x10\x02\x12\x14\n" +
	"\x10QUANTILE_TYPE_80\x10\x03\x12\x14\n" +
	"\x10QUANTILE_TYPE_85\x10\x04\x12\x14\n" +
	"\x10QUANTILE_TYPE_90\x10\x05\x12\x14\n" +
	"\x10QUANTILE_TYPE_95\x10\x06\x12\x14\n" +
	"\x10QUANTILE_TYPE_98\x10\a\x12\x14\n" +
	"\x10QUANTILE_TYPE_99\x10\b\x12\x15\n" +
	"\x11QUANTILE_TYPE_100\x10\tB\x7f\n" +
	"*yandex.cloud.api.loadtesting.api.v1.commonZQgithub.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1/common;commonb\x06proto3"

var (
	file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescOnce sync.Once
	file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescData []byte
)

func file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescGZIP() []byte {
	file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDesc), len(file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDesc)))
	})
	return file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDescData
}

var file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_goTypes = []any{
	(QuantileType)(0), // 0: yandex.cloud.loadtesting.api.v1.common.QuantileType
	(*Quantiles)(nil), // 1: yandex.cloud.loadtesting.api.v1.common.Quantiles
}
var file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_init() }
func file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_init() {
	if File_yandex_cloud_loadtesting_api_v1_common_quantiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDesc), len(file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_msgTypes,
	}.Build()
	File_yandex_cloud_loadtesting_api_v1_common_quantiles_proto = out.File
	file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_goTypes = nil
	file_yandex_cloud_loadtesting_api_v1_common_quantiles_proto_depIdxs = nil
}
