// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: yandex/cloud/ai/assistants/v1/users/user.proto

package users

import (
	common "github.com/yandex-cloud/go-genproto/yandex/cloud/ai/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the user.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the folder that the user belongs to.
	FolderId string `protobuf:"bytes,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	// Name of the user.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the user.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Source      string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Identifier of the subject who created this user.
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Timestamp representing when the user was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Identifier of the subject who last updated this user.
	UpdatedBy string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// Timestamp representing the last time this user was updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Configuration for the expiration of the user, defining when and how the user will expire.
	ExpirationConfig *common.ExpirationConfig `protobuf:"bytes,10,opt,name=expiration_config,json=expirationConfig,proto3" json:"expiration_config,omitempty"`
	// Timestamp representing when the user will expire.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Set of key-value pairs that can be used to organize and categorize the user.
	Labels        map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_yandex_cloud_ai_assistants_v1_users_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_ai_assistants_v1_users_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *User) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *User) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetExpirationConfig() *common.ExpirationConfig {
	if x != nil {
		return x.ExpirationConfig
	}
	return nil
}

func (x *User) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *User) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_yandex_cloud_ai_assistants_v1_users_user_proto protoreflect.FileDescriptor

const file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDesc = "" +
	"\n" +
	".yandex/cloud/ai/assistants/v1/users/user.proto\x12#yandex.cloud.ai.assistants.v1.users\x1a#yandex/cloud/ai/common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\tR\bfolderId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12U\n" +
	"\x11expiration_config\x18\n" +
	" \x01(\v2(.yandex.cloud.ai.common.ExpirationConfigR\x10expirationConfig\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12M\n" +
	"\x06labels\x18\f \x03(\v25.yandex.cloud.ai.assistants.v1.users.User.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01Bx\n" +
	"'yandex.cloud.api.ai.assistants.v1.usersZMgithub.com/yandex-cloud/go-genproto/yandex/cloud/ai/assistants/v1/users;usersb\x06proto3"

var (
	file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescOnce sync.Once
	file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescData []byte
)

func file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescGZIP() []byte {
	file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDesc), len(file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDesc)))
	})
	return file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDescData
}

var file_yandex_cloud_ai_assistants_v1_users_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yandex_cloud_ai_assistants_v1_users_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: yandex.cloud.ai.assistants.v1.users.User
	nil,                             // 1: yandex.cloud.ai.assistants.v1.users.User.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
	(*common.ExpirationConfig)(nil), // 3: yandex.cloud.ai.common.ExpirationConfig
}
var file_yandex_cloud_ai_assistants_v1_users_user_proto_depIdxs = []int32{
	2, // 0: yandex.cloud.ai.assistants.v1.users.User.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: yandex.cloud.ai.assistants.v1.users.User.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: yandex.cloud.ai.assistants.v1.users.User.expiration_config:type_name -> yandex.cloud.ai.common.ExpirationConfig
	2, // 3: yandex.cloud.ai.assistants.v1.users.User.expires_at:type_name -> google.protobuf.Timestamp
	1, // 4: yandex.cloud.ai.assistants.v1.users.User.labels:type_name -> yandex.cloud.ai.assistants.v1.users.User.LabelsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_yandex_cloud_ai_assistants_v1_users_user_proto_init() }
func file_yandex_cloud_ai_assistants_v1_users_user_proto_init() {
	if File_yandex_cloud_ai_assistants_v1_users_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDesc), len(file_yandex_cloud_ai_assistants_v1_users_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_ai_assistants_v1_users_user_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_ai_assistants_v1_users_user_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_ai_assistants_v1_users_user_proto_msgTypes,
	}.Build()
	File_yandex_cloud_ai_assistants_v1_users_user_proto = out.File
	file_yandex_cloud_ai_assistants_v1_users_user_proto_goTypes = nil
	file_yandex_cloud_ai_assistants_v1_users_user_proto_depIdxs = nil
}
