// Code generated by protoc-gen-goext. DO NOT EDIT.

package usageRecords

func (m *LabelList) SetValues(v []string) {
	m.Values = v
}

func (m *BillingAccount) SetId(v string) {
	m.Id = v
}

func (m *BillingAccount) SetName(v string) {
	m.Name = v
}

func (m *Cloud) SetId(v string) {
	m.Id = v
}

func (m *Cloud) SetName(v string) {
	m.Name = v
}

func (m *Folder) SetId(v string) {
	m.Id = v
}

func (m *Folder) SetName(v string) {
	m.Name = v
}

func (m *Service) SetId(v string) {
	m.Id = v
}

func (m *Service) SetName(v string) {
	m.Name = v
}

func (m *Service) SetDescription(v string) {
	m.Description = v
}

func (m *SKU) SetId(v string) {
	m.Id = v
}

func (m *SKU) SetName(v string) {
	m.Name = v
}

func (m *SKU) SetRuTranslation(v string) {
	m.RuTranslation = v
}

func (m *SKU) SetEnTranslation(v string) {
	m.EnTranslation = v
}

func (m *SKU) SetPricingUnit(v string) {
	m.PricingUnit = v
}

func (m *SKU) SetServiceId(v string) {
	m.ServiceId = v
}

func (m *Resource) SetId(v string) {
	m.Id = v
}

func (m *Label) SetKey(v string) {
	m.Key = v
}

func (m *Label) SetValue(v string) {
	m.Value = v
}
