// Code generated by protoc-gen-goext. DO NOT EDIT.

package usageRecords

func (m *CreditDetails) SetCredit(v *StringDecimal) {
	m.Credit = v
}

func (m *CreditDetails) SetMonetaryGrantCredit(v *StringDecimal) {
	m.MonetaryGrantCredit = v
}

func (m *CreditDetails) SetVolumeIncentiveCredit(v *StringDecimal) {
	m.VolumeIncentiveCredit = v
}

func (m *CreditDetails) SetCudCredit(v *StringDecimal) {
	m.CudCredit = v
}

func (m *CreditDetails) SetFreeCredit(v *StringDecimal) {
	m.FreeCredit = v
}
