// Code generated by protoc-gen-goext. DO NOT EDIT.

package licensemanager

func (m *GetLockRequest) SetLockId(v string) {
	m.LockId = v
}

func (m *CreateLockRequest) SetInstanceId(v string) {
	m.InstanceId = v
}

func (m *CreateLockRequest) SetResourceId(v string) {
	m.ResourceId = v
}

func (m *CreateLockMetadata) SetLockId(v string) {
	m.LockId = v
}

func (m *EnsureLockMetadata) SetLockId(v string) {
	m.LockId = v
}

func (m *DeleteLockRequest) SetLockId(v string) {
	m.LockId = v
}

func (m *DeleteLockMetadata) SetLockId(v string) {
	m.LockId = v
}

func (m *GetLockByInstanceAndResourceRequest) SetInstanceId(v string) {
	m.InstanceId = v
}

func (m *GetLockByInstanceAndResourceRequest) SetResourceId(v string) {
	m.ResourceId = v
}
