// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: yandex/cloud/cic/v1/trunk_connection_ticket_service.proto

package cic

import (
	context "context"
	operation "github.com/yandex-cloud/go-genproto/yandex/cloud/operation"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrunkConnectionTicketService_Create_FullMethodName = "/yandex.cloud.cic.v1.TrunkConnectionTicketService/Create"
	TrunkConnectionTicketService_Revoke_FullMethodName = "/yandex.cloud.cic.v1.TrunkConnectionTicketService/Revoke"
	TrunkConnectionTicketService_Get_FullMethodName    = "/yandex.cloud.cic.v1.TrunkConnectionTicketService/Get"
	TrunkConnectionTicketService_List_FullMethodName   = "/yandex.cloud.cic.v1.TrunkConnectionTicketService/List"
)

// TrunkConnectionTicketServiceClient is the client API for TrunkConnectionTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A set of methods for managing TrunkConnectionTicket resources.
type TrunkConnectionTicketServiceClient interface {
	// Creates a TrunkConnectionTicket in the specified folder and opens a support ticket.
	Create(ctx context.Context, in *CreateTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Revokes a TrunkConnectionTicket and closes the underlying support ticket.
	Revoke(ctx context.Context, in *RevokeTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*operation.Operation, error)
	// Returns the specified TrunkConnectionTicket resource.
	Get(ctx context.Context, in *GetTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*TrunkConnectionTicket, error)
	// Lists TrunkConnectionTicket resources in the specified folder.
	List(ctx context.Context, in *ListTrunkConnectionTicketsRequest, opts ...grpc.CallOption) (*ListTrunkConnectionTicketsResponse, error)
}

type trunkConnectionTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrunkConnectionTicketServiceClient(cc grpc.ClientConnInterface) TrunkConnectionTicketServiceClient {
	return &trunkConnectionTicketServiceClient{cc}
}

func (c *trunkConnectionTicketServiceClient) Create(ctx context.Context, in *CreateTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, TrunkConnectionTicketService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trunkConnectionTicketServiceClient) Revoke(ctx context.Context, in *RevokeTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*operation.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(operation.Operation)
	err := c.cc.Invoke(ctx, TrunkConnectionTicketService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trunkConnectionTicketServiceClient) Get(ctx context.Context, in *GetTrunkConnectionTicketRequest, opts ...grpc.CallOption) (*TrunkConnectionTicket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrunkConnectionTicket)
	err := c.cc.Invoke(ctx, TrunkConnectionTicketService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trunkConnectionTicketServiceClient) List(ctx context.Context, in *ListTrunkConnectionTicketsRequest, opts ...grpc.CallOption) (*ListTrunkConnectionTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrunkConnectionTicketsResponse)
	err := c.cc.Invoke(ctx, TrunkConnectionTicketService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrunkConnectionTicketServiceServer is the server API for TrunkConnectionTicketService service.
// All implementations should embed UnimplementedTrunkConnectionTicketServiceServer
// for forward compatibility.
//
// A set of methods for managing TrunkConnectionTicket resources.
type TrunkConnectionTicketServiceServer interface {
	// Creates a TrunkConnectionTicket in the specified folder and opens a support ticket.
	Create(context.Context, *CreateTrunkConnectionTicketRequest) (*operation.Operation, error)
	// Revokes a TrunkConnectionTicket and closes the underlying support ticket.
	Revoke(context.Context, *RevokeTrunkConnectionTicketRequest) (*operation.Operation, error)
	// Returns the specified TrunkConnectionTicket resource.
	Get(context.Context, *GetTrunkConnectionTicketRequest) (*TrunkConnectionTicket, error)
	// Lists TrunkConnectionTicket resources in the specified folder.
	List(context.Context, *ListTrunkConnectionTicketsRequest) (*ListTrunkConnectionTicketsResponse, error)
}

// UnimplementedTrunkConnectionTicketServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrunkConnectionTicketServiceServer struct{}

func (UnimplementedTrunkConnectionTicketServiceServer) Create(context.Context, *CreateTrunkConnectionTicketRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTrunkConnectionTicketServiceServer) Revoke(context.Context, *RevokeTrunkConnectionTicketRequest) (*operation.Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedTrunkConnectionTicketServiceServer) Get(context.Context, *GetTrunkConnectionTicketRequest) (*TrunkConnectionTicket, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTrunkConnectionTicketServiceServer) List(context.Context, *ListTrunkConnectionTicketsRequest) (*ListTrunkConnectionTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTrunkConnectionTicketServiceServer) testEmbeddedByValue() {}

// UnsafeTrunkConnectionTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrunkConnectionTicketServiceServer will
// result in compilation errors.
type UnsafeTrunkConnectionTicketServiceServer interface {
	mustEmbedUnimplementedTrunkConnectionTicketServiceServer()
}

func RegisterTrunkConnectionTicketServiceServer(s grpc.ServiceRegistrar, srv TrunkConnectionTicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTrunkConnectionTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrunkConnectionTicketService_ServiceDesc, srv)
}

func _TrunkConnectionTicketService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrunkConnectionTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrunkConnectionTicketServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrunkConnectionTicketService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrunkConnectionTicketServiceServer).Create(ctx, req.(*CreateTrunkConnectionTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrunkConnectionTicketService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTrunkConnectionTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrunkConnectionTicketServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrunkConnectionTicketService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrunkConnectionTicketServiceServer).Revoke(ctx, req.(*RevokeTrunkConnectionTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrunkConnectionTicketService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrunkConnectionTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrunkConnectionTicketServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrunkConnectionTicketService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrunkConnectionTicketServiceServer).Get(ctx, req.(*GetTrunkConnectionTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrunkConnectionTicketService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrunkConnectionTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrunkConnectionTicketServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrunkConnectionTicketService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrunkConnectionTicketServiceServer).List(ctx, req.(*ListTrunkConnectionTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrunkConnectionTicketService_ServiceDesc is the grpc.ServiceDesc for TrunkConnectionTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrunkConnectionTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yandex.cloud.cic.v1.TrunkConnectionTicketService",
	HandlerType: (*TrunkConnectionTicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TrunkConnectionTicketService_Create_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _TrunkConnectionTicketService_Revoke_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TrunkConnectionTicketService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TrunkConnectionTicketService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yandex/cloud/cic/v1/trunk_connection_ticket_service.proto",
}
