// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: yandex/cloud/ai/tuning/v1/tuning_optimizers.proto

package fomo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizerAdamw struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beta1       float64 `protobuf:"fixed64,1,opt,name=beta1,proto3" json:"beta1,omitempty"`
	Beta2       float64 `protobuf:"fixed64,2,opt,name=beta2,proto3" json:"beta2,omitempty"`
	Eps         float64 `protobuf:"fixed64,3,opt,name=eps,proto3" json:"eps,omitempty"`
	WeightDecay float64 `protobuf:"fixed64,4,opt,name=weight_decay,json=weightDecay,proto3" json:"weight_decay,omitempty"`
}

func (x *OptimizerAdamw) Reset() {
	*x = OptimizerAdamw{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptimizerAdamw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizerAdamw) ProtoMessage() {}

func (x *OptimizerAdamw) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizerAdamw.ProtoReflect.Descriptor instead.
func (*OptimizerAdamw) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizerAdamw) GetBeta1() float64 {
	if x != nil {
		return x.Beta1
	}
	return 0
}

func (x *OptimizerAdamw) GetBeta2() float64 {
	if x != nil {
		return x.Beta2
	}
	return 0
}

func (x *OptimizerAdamw) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *OptimizerAdamw) GetWeightDecay() float64 {
	if x != nil {
		return x.WeightDecay
	}
	return 0
}

var File_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto protoreflect.FileDescriptor

var file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDesc = []byte{
	0x0a, 0x31, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61,
	0x69, 0x2f, 0x74, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x75, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x61, 0x69, 0x2e, 0x74, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x71,
	0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x41, 0x64, 0x61, 0x6d, 0x77,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x74, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x62, 0x65, 0x74, 0x61, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x74, 0x61, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x62, 0x65, 0x74, 0x61, 0x32, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x65, 0x70, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x64, 0x65, 0x63, 0x61, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x44, 0x65, 0x63, 0x61,
	0x79, 0x42, 0x63, 0x0a, 0x1d, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x69, 0x2e, 0x74, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x67, 0x6f, 0x2d, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x69, 0x2f, 0x74, 0x75, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x76,
	0x31, 0x3b, 0x66, 0x6f, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescOnce sync.Once
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescData = file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDesc
)

func file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescGZIP() []byte {
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescData = protoimpl.X.CompressGZIP(file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescData)
	})
	return file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDescData
}

var file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_goTypes = []any{
	(*OptimizerAdamw)(nil), // 0: yandex.cloud.ai.tuning.v1.OptimizerAdamw
}
var file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_init() }
func file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_init() {
	if File_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OptimizerAdamw); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_msgTypes,
	}.Build()
	File_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto = out.File
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_rawDesc = nil
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_goTypes = nil
	file_yandex_cloud_ai_tuning_v1_tuning_optimizers_proto_depIdxs = nil
}
