// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yandex/cloud/loadtesting/agent/v1/job_service.proto

package agent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimJobStatusRequest_JobStatus int32

const (
	ClaimJobStatusRequest_JOB_STATUS_UNSPECIFIED ClaimJobStatusRequest_JobStatus = 0
	ClaimJobStatusRequest_POST_PROCESS           ClaimJobStatusRequest_JobStatus = 1
	ClaimJobStatusRequest_INITIATED              ClaimJobStatusRequest_JobStatus = 2
	ClaimJobStatusRequest_PREPARING              ClaimJobStatusRequest_JobStatus = 3
	// Deprecated: Marked as deprecated in yandex/cloud/loadtesting/agent/v1/job_service.proto.
	ClaimJobStatusRequest_NOT_FOUND                    ClaimJobStatusRequest_JobStatus = 4
	ClaimJobStatusRequest_RUNNING                      ClaimJobStatusRequest_JobStatus = 5
	ClaimJobStatusRequest_FINISHING                    ClaimJobStatusRequest_JobStatus = 6
	ClaimJobStatusRequest_FINISHED                     ClaimJobStatusRequest_JobStatus = 7
	ClaimJobStatusRequest_STOPPED                      ClaimJobStatusRequest_JobStatus = 8
	ClaimJobStatusRequest_FAILED                       ClaimJobStatusRequest_JobStatus = 9
	ClaimJobStatusRequest_AUTOSTOPPED                  ClaimJobStatusRequest_JobStatus = 10
	ClaimJobStatusRequest_WAITING_FOR_A_COMMAND_TO_RUN ClaimJobStatusRequest_JobStatus = 11
)

// Enum value maps for ClaimJobStatusRequest_JobStatus.
var (
	ClaimJobStatusRequest_JobStatus_name = map[int32]string{
		0:  "JOB_STATUS_UNSPECIFIED",
		1:  "POST_PROCESS",
		2:  "INITIATED",
		3:  "PREPARING",
		4:  "NOT_FOUND",
		5:  "RUNNING",
		6:  "FINISHING",
		7:  "FINISHED",
		8:  "STOPPED",
		9:  "FAILED",
		10: "AUTOSTOPPED",
		11: "WAITING_FOR_A_COMMAND_TO_RUN",
	}
	ClaimJobStatusRequest_JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED":       0,
		"POST_PROCESS":                 1,
		"INITIATED":                    2,
		"PREPARING":                    3,
		"NOT_FOUND":                    4,
		"RUNNING":                      5,
		"FINISHING":                    6,
		"FINISHED":                     7,
		"STOPPED":                      8,
		"FAILED":                       9,
		"AUTOSTOPPED":                  10,
		"WAITING_FOR_A_COMMAND_TO_RUN": 11,
	}
)

func (x ClaimJobStatusRequest_JobStatus) Enum() *ClaimJobStatusRequest_JobStatus {
	p := new(ClaimJobStatusRequest_JobStatus)
	*p = x
	return p
}

func (x ClaimJobStatusRequest_JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimJobStatusRequest_JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes[0].Descriptor()
}

func (ClaimJobStatusRequest_JobStatus) Type() protoreflect.EnumType {
	return &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes[0]
}

func (x ClaimJobStatusRequest_JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimJobStatusRequest_JobStatus.Descriptor instead.
func (ClaimJobStatusRequest_JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{7, 0}
}

type JobSignalResponse_Signal int32

const (
	JobSignalResponse_SIGNAL_UNSPECIFIED JobSignalResponse_Signal = 0
	JobSignalResponse_STOP               JobSignalResponse_Signal = 1
	JobSignalResponse_WAIT               JobSignalResponse_Signal = 2
	JobSignalResponse_RUN_IN             JobSignalResponse_Signal = 3
)

// Enum value maps for JobSignalResponse_Signal.
var (
	JobSignalResponse_Signal_name = map[int32]string{
		0: "SIGNAL_UNSPECIFIED",
		1: "STOP",
		2: "WAIT",
		3: "RUN_IN",
	}
	JobSignalResponse_Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"STOP":               1,
		"WAIT":               2,
		"RUN_IN":             3,
	}
)

func (x JobSignalResponse_Signal) Enum() *JobSignalResponse_Signal {
	p := new(JobSignalResponse_Signal)
	*p = x
	return p
}

func (x JobSignalResponse_Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobSignalResponse_Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes[1].Descriptor()
}

func (JobSignalResponse_Signal) Type() protoreflect.EnumType {
	return &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes[1]
}

func (x JobSignalResponse_Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobSignalResponse_Signal.Descriptor instead.
func (JobSignalResponse_Signal) EnumDescriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{10, 0}
}

type Job struct {
	state                  protoimpl.MessageState      `protogen:"open.v1"`
	Id                     string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config                 string                      `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Ammo                   *File                       `protobuf:"bytes,3,opt,name=ammo,proto3" json:"ammo,omitempty"`
	LoggingLogGroupId      string                      `protobuf:"bytes,4,opt,name=logging_log_group_id,json=loggingLogGroupId,proto3" json:"logging_log_group_id,omitempty"`
	TestData               *StorageObject              `protobuf:"bytes,5,opt,name=test_data,json=testData,proto3" json:"test_data,omitempty"`
	DataPayload            []*TestDataEntry            `protobuf:"bytes,6,rep,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"`
	ArtifactUploadSettings *TestArtifactUploadSettings `protobuf:"bytes,7,opt,name=artifact_upload_settings,json=artifactUploadSettings,proto3" json:"artifact_upload_settings,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Job) GetAmmo() *File {
	if x != nil {
		return x.Ammo
	}
	return nil
}

func (x *Job) GetLoggingLogGroupId() string {
	if x != nil {
		return x.LoggingLogGroupId
	}
	return ""
}

func (x *Job) GetTestData() *StorageObject {
	if x != nil {
		return x.TestData
	}
	return nil
}

func (x *Job) GetDataPayload() []*TestDataEntry {
	if x != nil {
		return x.DataPayload
	}
	return nil
}

func (x *Job) GetArtifactUploadSettings() *TestArtifactUploadSettings {
	if x != nil {
		return x.ArtifactUploadSettings
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StorageObject struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ObjectStorageBucket   string                 `protobuf:"bytes,1,opt,name=object_storage_bucket,json=objectStorageBucket,proto3" json:"object_storage_bucket,omitempty"`
	ObjectStorageFilename string                 `protobuf:"bytes,2,opt,name=object_storage_filename,json=objectStorageFilename,proto3" json:"object_storage_filename,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StorageObject) Reset() {
	*x = StorageObject{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObject) ProtoMessage() {}

func (x *StorageObject) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObject.ProtoReflect.Descriptor instead.
func (*StorageObject) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{2}
}

func (x *StorageObject) GetObjectStorageBucket() string {
	if x != nil {
		return x.ObjectStorageBucket
	}
	return ""
}

func (x *StorageObject) GetObjectStorageFilename() string {
	if x != nil {
		return x.ObjectStorageFilename
	}
	return ""
}

type TestDataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsTransient   bool                   `protobuf:"varint,2,opt,name=is_transient,json=isTransient,proto3" json:"is_transient,omitempty"`
	StorageObject *StorageObject         `protobuf:"bytes,3,opt,name=storage_object,json=storageObject,proto3" json:"storage_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestDataEntry) Reset() {
	*x = TestDataEntry{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestDataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDataEntry) ProtoMessage() {}

func (x *TestDataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDataEntry.ProtoReflect.Descriptor instead.
func (*TestDataEntry) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{3}
}

func (x *TestDataEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestDataEntry) GetIsTransient() bool {
	if x != nil {
		return x.IsTransient
	}
	return false
}

func (x *TestDataEntry) GetStorageObject() *StorageObject {
	if x != nil {
		return x.StorageObject
	}
	return nil
}

type TestArtifactUploadSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputBucket  string                 `protobuf:"bytes,1,opt,name=output_bucket,json=outputBucket,proto3" json:"output_bucket,omitempty"`
	OutputName    string                 `protobuf:"bytes,2,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	IsArchive     bool                   `protobuf:"varint,3,opt,name=is_archive,json=isArchive,proto3" json:"is_archive,omitempty"`
	FilterInclude []string               `protobuf:"bytes,4,rep,name=filter_include,json=filterInclude,proto3" json:"filter_include,omitempty"`
	FilterExclude []string               `protobuf:"bytes,5,rep,name=filter_exclude,json=filterExclude,proto3" json:"filter_exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestArtifactUploadSettings) Reset() {
	*x = TestArtifactUploadSettings{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestArtifactUploadSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestArtifactUploadSettings) ProtoMessage() {}

func (x *TestArtifactUploadSettings) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestArtifactUploadSettings.ProtoReflect.Descriptor instead.
func (*TestArtifactUploadSettings) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{4}
}

func (x *TestArtifactUploadSettings) GetOutputBucket() string {
	if x != nil {
		return x.OutputBucket
	}
	return ""
}

func (x *TestArtifactUploadSettings) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

func (x *TestArtifactUploadSettings) GetIsArchive() bool {
	if x != nil {
		return x.IsArchive
	}
	return false
}

func (x *TestArtifactUploadSettings) GetFilterInclude() []string {
	if x != nil {
		return x.FilterInclude
	}
	return nil
}

func (x *TestArtifactUploadSettings) GetFilterExclude() []string {
	if x != nil {
		return x.FilterExclude
	}
	return nil
}

type GetJobTransientFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobTransientFile) Reset() {
	*x = GetJobTransientFile{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobTransientFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobTransientFile) ProtoMessage() {}

func (x *GetJobTransientFile) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobTransientFile.ProtoReflect.Descriptor instead.
func (*GetJobTransientFile) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobTransientFile) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobTransientFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetJobRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ComputeInstanceId string                 `protobuf:"bytes,1,opt,name=compute_instance_id,json=computeInstanceId,proto3" json:"compute_instance_id,omitempty"`
	AgentInstanceId   string                 `protobuf:"bytes,2,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	JobId             string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobRequest) GetComputeInstanceId() string {
	if x != nil {
		return x.ComputeInstanceId
	}
	return ""
}

func (x *GetJobRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ClaimJobStatusRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	JobId         string                          `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        ClaimJobStatusRequest_JobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest_JobStatus" json:"status,omitempty"`
	Error         string                          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobStatusRequest) Reset() {
	*x = ClaimJobStatusRequest{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobStatusRequest) ProtoMessage() {}

func (x *ClaimJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobStatusRequest.ProtoReflect.Descriptor instead.
func (*ClaimJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ClaimJobStatusRequest) GetStatus() ClaimJobStatusRequest_JobStatus {
	if x != nil {
		return x.Status
	}
	return ClaimJobStatusRequest_JOB_STATUS_UNSPECIFIED
}

func (x *ClaimJobStatusRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClaimJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobStatusResponse) Reset() {
	*x = ClaimJobStatusResponse{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobStatusResponse) ProtoMessage() {}

func (x *ClaimJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobStatusResponse.ProtoReflect.Descriptor instead.
func (*ClaimJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimJobStatusResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type JobSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSignalRequest) Reset() {
	*x = JobSignalRequest{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSignalRequest) ProtoMessage() {}

func (x *JobSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSignalRequest.ProtoReflect.Descriptor instead.
func (*JobSignalRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{9}
}

func (x *JobSignalRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobSignalResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Signal        JobSignalResponse_Signal `protobuf:"varint,1,opt,name=signal,proto3,enum=yandex.cloud.loadtesting.agent.v1.JobSignalResponse_Signal" json:"signal,omitempty"`
	WaitDuration  float64                  `protobuf:"fixed64,2,opt,name=wait_duration,json=waitDuration,proto3" json:"wait_duration,omitempty"` // seconds
	RunIn         float64                  `protobuf:"fixed64,3,opt,name=run_in,json=runIn,proto3" json:"run_in,omitempty"`                      // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSignalResponse) Reset() {
	*x = JobSignalResponse{}
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSignalResponse) ProtoMessage() {}

func (x *JobSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSignalResponse.ProtoReflect.Descriptor instead.
func (*JobSignalResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP(), []int{10}
}

func (x *JobSignalResponse) GetSignal() JobSignalResponse_Signal {
	if x != nil {
		return x.Signal
	}
	return JobSignalResponse_SIGNAL_UNSPECIFIED
}

func (x *JobSignalResponse) GetWaitDuration() float64 {
	if x != nil {
		return x.WaitDuration
	}
	return 0
}

func (x *JobSignalResponse) GetRunIn() float64 {
	if x != nil {
		return x.RunIn
	}
	return 0
}

var File_yandex_cloud_loadtesting_agent_v1_job_service_proto protoreflect.FileDescriptor

const file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDesc = "" +
	"\n" +
	"3yandex/cloud/loadtesting/agent/v1/job_service.proto\x12!yandex.cloud.loadtesting.agent.v1\x1a\x1cgoogle/api/annotations.proto\"\xb8\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12;\n" +
	"\x04ammo\x18\x03 \x01(\v2'.yandex.cloud.loadtesting.agent.v1.FileR\x04ammo\x12/\n" +
	"\x14logging_log_group_id\x18\x04 \x01(\tR\x11loggingLogGroupId\x12M\n" +
	"\ttest_data\x18\x05 \x01(\v20.yandex.cloud.loadtesting.agent.v1.StorageObjectR\btestData\x12S\n" +
	"\fdata_payload\x18\x06 \x03(\v20.yandex.cloud.loadtesting.agent.v1.TestDataEntryR\vdataPayload\x12w\n" +
	"\x18artifact_upload_settings\x18\a \x01(\v2=.yandex.cloud.loadtesting.agent.v1.TestArtifactUploadSettingsR\x16artifactUploadSettings\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"{\n" +
	"\rStorageObject\x122\n" +
	"\x15object_storage_bucket\x18\x01 \x01(\tR\x13objectStorageBucket\x126\n" +
	"\x17object_storage_filename\x18\x02 \x01(\tR\x15objectStorageFilename\"\x9f\x01\n" +
	"\rTestDataEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_transient\x18\x02 \x01(\bR\visTransient\x12W\n" +
	"\x0estorage_object\x18\x03 \x01(\v20.yandex.cloud.loadtesting.agent.v1.StorageObjectR\rstorageObject\"\xcf\x01\n" +
	"\x1aTestArtifactUploadSettings\x12#\n" +
	"\routput_bucket\x18\x01 \x01(\tR\foutputBucket\x12\x1f\n" +
	"\voutput_name\x18\x02 \x01(\tR\n" +
	"outputName\x12\x1d\n" +
	"\n" +
	"is_archive\x18\x03 \x01(\bR\tisArchive\x12%\n" +
	"\x0efilter_include\x18\x04 \x03(\tR\rfilterInclude\x12%\n" +
	"\x0efilter_exclude\x18\x05 \x03(\tR\rfilterExclude\"@\n" +
	"\x13GetJobTransientFile\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x82\x01\n" +
	"\rGetJobRequest\x12.\n" +
	"\x13compute_instance_id\x18\x01 \x01(\tR\x11computeInstanceId\x12*\n" +
	"\x11agent_instance_id\x18\x02 \x01(\tR\x0fagentInstanceId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"\x83\x03\n" +
	"\x15ClaimJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12Z\n" +
	"\x06status\x18\x02 \x01(\x0e2B.yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest.JobStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xe0\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPOST_PROCESS\x10\x01\x12\r\n" +
	"\tINITIATED\x10\x02\x12\r\n" +
	"\tPREPARING\x10\x03\x12\x11\n" +
	"\tNOT_FOUND\x10\x04\x1a\x02\b\x01\x12\v\n" +
	"\aRUNNING\x10\x05\x12\r\n" +
	"\tFINISHING\x10\x06\x12\f\n" +
	"\bFINISHED\x10\a\x12\v\n" +
	"\aSTOPPED\x10\b\x12\n" +
	"\n" +
	"\x06FAILED\x10\t\x12\x0f\n" +
	"\vAUTOSTOPPED\x10\n" +
	"\x12 \n" +
	"\x1cWAITING_FOR_A_COMMAND_TO_RUN\x10\v\",\n" +
	"\x16ClaimJobStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\")\n" +
	"\x10JobSignalRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xe6\x01\n" +
	"\x11JobSignalResponse\x12S\n" +
	"\x06signal\x18\x01 \x01(\x0e2;.yandex.cloud.loadtesting.agent.v1.JobSignalResponse.SignalR\x06signal\x12#\n" +
	"\rwait_duration\x18\x02 \x01(\x01R\fwaitDuration\x12\x15\n" +
	"\x06run_in\x18\x03 \x01(\x01R\x05runIn\"@\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\b\n" +
	"\x04WAIT\x10\x02\x12\n" +
	"\n" +
	"\x06RUN_IN\x10\x032\xfb\x05\n" +
	"\n" +
	"JobService\x12\xbe\x01\n" +
	"\vClaimStatus\x128.yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest\x1a9.yandex.cloud.loadtesting.agent.v1.ClaimJobStatusResponse\":\x82\xd3\xe4\x93\x024:\x01*\"//loadtesting/agent/v1/jobs/{job_id}/claimStatus\x12\xc7\x01\n" +
	"\x03Get\x120.yandex.cloud.loadtesting.agent.v1.GetJobRequest\x1a&.yandex.cloud.loadtesting.agent.v1.Job\"f\x82\xd3\xe4\x93\x02`Z%\x12#/loadtesting/agent/v1/jobs/{job_id}\x127/loadtesting/agent/v1/agents/{agent_instance_id}/getJob\x12\xad\x01\n" +
	"\tGetSignal\x123.yandex.cloud.loadtesting.agent.v1.JobSignalRequest\x1a4.yandex.cloud.loadtesting.agent.v1.JobSignalResponse\"5\x82\xd3\xe4\x93\x02/\x12-/loadtesting/agent/v1/jobs/{job_id}/getSignal\x12\xb1\x01\n" +
	"\x10GetTransientFile\x126.yandex.cloud.loadtesting.agent.v1.GetJobTransientFile\x1a'.yandex.cloud.loadtesting.agent.v1.File\"<\x82\xd3\xe4\x93\x026\x124/loadtesting/agent/v1/jobs/{job_id}/getTransientFileBt\n" +
	"%yandex.cloud.api.loadtesting.agent.v1ZKgithub.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/agent/v1;agentb\x06proto3"

var (
	file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescOnce sync.Once
	file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescData []byte
)

func file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescGZIP() []byte {
	file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDesc), len(file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDesc)))
	})
	return file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDescData
}

var file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_yandex_cloud_loadtesting_agent_v1_job_service_proto_goTypes = []any{
	(ClaimJobStatusRequest_JobStatus)(0), // 0: yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest.JobStatus
	(JobSignalResponse_Signal)(0),        // 1: yandex.cloud.loadtesting.agent.v1.JobSignalResponse.Signal
	(*Job)(nil),                          // 2: yandex.cloud.loadtesting.agent.v1.Job
	(*File)(nil),                         // 3: yandex.cloud.loadtesting.agent.v1.File
	(*StorageObject)(nil),                // 4: yandex.cloud.loadtesting.agent.v1.StorageObject
	(*TestDataEntry)(nil),                // 5: yandex.cloud.loadtesting.agent.v1.TestDataEntry
	(*TestArtifactUploadSettings)(nil),   // 6: yandex.cloud.loadtesting.agent.v1.TestArtifactUploadSettings
	(*GetJobTransientFile)(nil),          // 7: yandex.cloud.loadtesting.agent.v1.GetJobTransientFile
	(*GetJobRequest)(nil),                // 8: yandex.cloud.loadtesting.agent.v1.GetJobRequest
	(*ClaimJobStatusRequest)(nil),        // 9: yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest
	(*ClaimJobStatusResponse)(nil),       // 10: yandex.cloud.loadtesting.agent.v1.ClaimJobStatusResponse
	(*JobSignalRequest)(nil),             // 11: yandex.cloud.loadtesting.agent.v1.JobSignalRequest
	(*JobSignalResponse)(nil),            // 12: yandex.cloud.loadtesting.agent.v1.JobSignalResponse
}
var file_yandex_cloud_loadtesting_agent_v1_job_service_proto_depIdxs = []int32{
	3,  // 0: yandex.cloud.loadtesting.agent.v1.Job.ammo:type_name -> yandex.cloud.loadtesting.agent.v1.File
	4,  // 1: yandex.cloud.loadtesting.agent.v1.Job.test_data:type_name -> yandex.cloud.loadtesting.agent.v1.StorageObject
	5,  // 2: yandex.cloud.loadtesting.agent.v1.Job.data_payload:type_name -> yandex.cloud.loadtesting.agent.v1.TestDataEntry
	6,  // 3: yandex.cloud.loadtesting.agent.v1.Job.artifact_upload_settings:type_name -> yandex.cloud.loadtesting.agent.v1.TestArtifactUploadSettings
	4,  // 4: yandex.cloud.loadtesting.agent.v1.TestDataEntry.storage_object:type_name -> yandex.cloud.loadtesting.agent.v1.StorageObject
	0,  // 5: yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest.status:type_name -> yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest.JobStatus
	1,  // 6: yandex.cloud.loadtesting.agent.v1.JobSignalResponse.signal:type_name -> yandex.cloud.loadtesting.agent.v1.JobSignalResponse.Signal
	9,  // 7: yandex.cloud.loadtesting.agent.v1.JobService.ClaimStatus:input_type -> yandex.cloud.loadtesting.agent.v1.ClaimJobStatusRequest
	8,  // 8: yandex.cloud.loadtesting.agent.v1.JobService.Get:input_type -> yandex.cloud.loadtesting.agent.v1.GetJobRequest
	11, // 9: yandex.cloud.loadtesting.agent.v1.JobService.GetSignal:input_type -> yandex.cloud.loadtesting.agent.v1.JobSignalRequest
	7,  // 10: yandex.cloud.loadtesting.agent.v1.JobService.GetTransientFile:input_type -> yandex.cloud.loadtesting.agent.v1.GetJobTransientFile
	10, // 11: yandex.cloud.loadtesting.agent.v1.JobService.ClaimStatus:output_type -> yandex.cloud.loadtesting.agent.v1.ClaimJobStatusResponse
	2,  // 12: yandex.cloud.loadtesting.agent.v1.JobService.Get:output_type -> yandex.cloud.loadtesting.agent.v1.Job
	12, // 13: yandex.cloud.loadtesting.agent.v1.JobService.GetSignal:output_type -> yandex.cloud.loadtesting.agent.v1.JobSignalResponse
	3,  // 14: yandex.cloud.loadtesting.agent.v1.JobService.GetTransientFile:output_type -> yandex.cloud.loadtesting.agent.v1.File
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_yandex_cloud_loadtesting_agent_v1_job_service_proto_init() }
func file_yandex_cloud_loadtesting_agent_v1_job_service_proto_init() {
	if File_yandex_cloud_loadtesting_agent_v1_job_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDesc), len(file_yandex_cloud_loadtesting_agent_v1_job_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yandex_cloud_loadtesting_agent_v1_job_service_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_loadtesting_agent_v1_job_service_proto_depIdxs,
		EnumInfos:         file_yandex_cloud_loadtesting_agent_v1_job_service_proto_enumTypes,
		MessageInfos:      file_yandex_cloud_loadtesting_agent_v1_job_service_proto_msgTypes,
	}.Build()
	File_yandex_cloud_loadtesting_agent_v1_job_service_proto = out.File
	file_yandex_cloud_loadtesting_agent_v1_job_service_proto_goTypes = nil
	file_yandex_cloud_loadtesting_agent_v1_job_service_proto_depIdxs = nil
}
