// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: yandex/cloud/loadtesting/api/v1/test/details.proto

package test

import (
	_ "github.com/yandex-cloud/go-genproto/yandex/cloud"
	common "github.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Test meta information.
type Details struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the test.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the test.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Tags assigned to the test.
	Tags []*common.Tag `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// ID of the logging group to which test artifacts are uploaded.
	LoggingLogGroupId string `protobuf:"bytes,4,opt,name=logging_log_group_id,json=loggingLogGroupId,proto3" json:"logging_log_group_id,omitempty"`
	// Settings which define where to upload test artifacts and which files should be included.
	ArtifactSettings *ArtifactSettings `protobuf:"bytes,5,opt,name=artifact_settings,json=artifactSettings,proto3" json:"artifact_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_yandex_cloud_loadtesting_api_v1_test_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_loadtesting_api_v1_test_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescGZIP(), []int{0}
}

func (x *Details) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Details) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Details) GetTags() []*common.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Details) GetLoggingLogGroupId() string {
	if x != nil {
		return x.LoggingLogGroupId
	}
	return ""
}

func (x *Details) GetArtifactSettings() *ArtifactSettings {
	if x != nil {
		return x.ArtifactSettings
	}
	return nil
}

var File_yandex_cloud_loadtesting_api_v1_test_details_proto protoreflect.FileDescriptor

const file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDesc = "" +
	"\n" +
	"2yandex/cloud/loadtesting/api/v1/test/details.proto\x12$yandex.cloud.loadtesting.api.v1.test\x1a0yandex/cloud/loadtesting/api/v1/common/tag.proto\x1a<yandex/cloud/loadtesting/api/v1/test/artifact_settings.proto\x1a\x1dyandex/cloud/validation.proto\"\xc7\x02\n" +
	"\aDetails\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xf2\xc71 |[a-z]([-a-z0-9]{0,61}[a-z0-9])?R\x04name\x12+\n" +
	"\vdescription\x18\x02 \x01(\tB\t\x8a\xc81\x05<=256R\vdescription\x12?\n" +
	"\x04tags\x18\x03 \x03(\v2+.yandex.cloud.loadtesting.api.v1.common.TagR\x04tags\x12/\n" +
	"\x14logging_log_group_id\x18\x04 \x01(\tR\x11loggingLogGroupId\x12c\n" +
	"\x11artifact_settings\x18\x05 \x01(\v26.yandex.cloud.loadtesting.api.v1.test.ArtifactSettingsR\x10artifactSettingsBy\n" +
	"(yandex.cloud.api.loadtesting.api.v1.testZMgithub.com/yandex-cloud/go-genproto/yandex/cloud/loadtesting/api/v1/test;testb\x06proto3"

var (
	file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescOnce sync.Once
	file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescData []byte
)

func file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescGZIP() []byte {
	file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDesc), len(file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDesc)))
	})
	return file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDescData
}

var file_yandex_cloud_loadtesting_api_v1_test_details_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yandex_cloud_loadtesting_api_v1_test_details_proto_goTypes = []any{
	(*Details)(nil),          // 0: yandex.cloud.loadtesting.api.v1.test.Details
	(*common.Tag)(nil),       // 1: yandex.cloud.loadtesting.api.v1.common.Tag
	(*ArtifactSettings)(nil), // 2: yandex.cloud.loadtesting.api.v1.test.ArtifactSettings
}
var file_yandex_cloud_loadtesting_api_v1_test_details_proto_depIdxs = []int32{
	1, // 0: yandex.cloud.loadtesting.api.v1.test.Details.tags:type_name -> yandex.cloud.loadtesting.api.v1.common.Tag
	2, // 1: yandex.cloud.loadtesting.api.v1.test.Details.artifact_settings:type_name -> yandex.cloud.loadtesting.api.v1.test.ArtifactSettings
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yandex_cloud_loadtesting_api_v1_test_details_proto_init() }
func file_yandex_cloud_loadtesting_api_v1_test_details_proto_init() {
	if File_yandex_cloud_loadtesting_api_v1_test_details_proto != nil {
		return
	}
	file_yandex_cloud_loadtesting_api_v1_test_artifact_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDesc), len(file_yandex_cloud_loadtesting_api_v1_test_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_loadtesting_api_v1_test_details_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_loadtesting_api_v1_test_details_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_loadtesting_api_v1_test_details_proto_msgTypes,
	}.Build()
	File_yandex_cloud_loadtesting_api_v1_test_details_proto = out.File
	file_yandex_cloud_loadtesting_api_v1_test_details_proto_goTypes = nil
	file_yandex_cloud_loadtesting_api_v1_test_details_proto_depIdxs = nil
}
